### Secret

# @name List Secrets
GET {{base-url}}/secret?list_params.page_size=10
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# @name Get Secret
GET {{base-url}}/secret/{{secret_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}
