// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/apikey.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiKeyMain struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UsrId     int64                  `protobuf:"varint,4,opt,name=usr_id,json=usrId,proto3" json:"usr_id,omitempty"`
	Active    bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	// При true ключ принимается только MCP-эндпоинтом; основной API его
	// отвергает. Рекомендуется для ключей AI-агентов.
	McpOnly bool   `protobuf:"varint,9,opt,name=mcp_only,json=mcpOnly,proto3" json:"mcp_only,omitempty"`
	Name    string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Первые символы ключа — для опознания; сам ключ не хранится.
	KeyPrefix     string                 `protobuf:"bytes,7,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyMain) Reset() {
	*x = ApiKeyMain{}
	mi := &file_kusec_v1_apikey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyMain) ProtoMessage() {}

func (x *ApiKeyMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_apikey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyMain.ProtoReflect.Descriptor instead.
func (*ApiKeyMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_apikey_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKeyMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKeyMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApiKeyMain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ApiKeyMain) GetUsrId() int64 {
	if x != nil {
		return x.UsrId
	}
	return 0
}

func (x *ApiKeyMain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ApiKeyMain) GetMcpOnly() bool {
	if x != nil {
		return x.McpOnly
	}
	return false
}

func (x *ApiKeyMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyMain) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *ApiKeyMain) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type ApiKeyListReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ListParams *ListParamsSt          `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	// Только для админов; не-админ всегда видит только свои ключи.
	UsrId         *int64 `protobuf:"varint,2,opt,name=usr_id,json=usrId,proto3,oneof" json:"usr_id,omitempty"`
	Active        *bool  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyListReq) Reset() {
	*x = ApiKeyListReq{}
	mi := &file_kusec_v1_apikey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyListReq) ProtoMessage() {}

func (x *ApiKeyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_apikey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyListReq.ProtoReflect.Descriptor instead.
func (*ApiKeyListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_apikey_proto_rawDescGZIP(), []int{1}
}

func (x *ApiKeyListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *ApiKeyListReq) GetUsrId() int64 {
	if x != nil && x.UsrId != nil {
		return *x.UsrId
	}
	return 0
}

func (x *ApiKeyListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type ApiKeyListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*ApiKeyMain          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiKeyListRep) Reset() {
	*x = ApiKeyListRep{}
	mi := &file_kusec_v1_apikey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyListRep) ProtoMessage() {}

func (x *ApiKeyListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_apikey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyListRep.ProtoReflect.Descriptor instead.
func (*ApiKeyListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_apikey_proto_rawDescGZIP(), []int{2}
}

func (x *ApiKeyListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *ApiKeyListRep) GetResults() []*ApiKeyMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type ApiKeyGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyGetReq) Reset() {
	*x = ApiKeyGetReq{}
	mi := &file_kusec_v1_apikey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyGetReq) ProtoMessage() {}

func (x *ApiKeyGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_apikey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyGetReq.ProtoReflect.Descriptor instead.
func (*ApiKeyGetReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_apikey_proto_rawDescGZIP(), []int{3}
}

func (x *ApiKeyGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApiKeyCreateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Только для админов; не-админ создаёт ключи только себе.
	UsrId *int64 `protobuf:"varint,2,opt,name=usr_id,json=usrId,proto3,oneof" json:"usr_id,omitempty"`
	// Ключ только для MCP-эндпоинта (рекомендуется для AI-агентов).
	McpOnly       bool `protobuf:"varint,3,opt,name=mcp_only,json=mcpOnly,proto3" json:"mcp_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyCreateReq) Reset() {
	*x = ApiKeyCreateReq{}
	mi := &file_kusec_v1_apikey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyCreateReq) ProtoMessage() {}

func (x *ApiKeyCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_apikey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyCreateReq.ProtoReflect.Descriptor instead.
func (*ApiKeyCreateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_apikey_proto_rawDescGZIP(), []int{4}
}

func (x *ApiKeyCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyCreateReq) GetUsrId() int64 {
	if x != nil && x.UsrId != nil {
		return *x.UsrId
	}
	return 0
}

func (x *ApiKeyCreateReq) GetMcpOnly() bool {
	if x != nil {
		return x.McpOnly
	}
	return false
}

type ApiKeyCreateRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Значение ключа; показывается только здесь, повторно получить нельзя.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyCreateRep) Reset() {
	*x = ApiKeyCreateRep{}
	mi := &file_kusec_v1_apikey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyCreateRep) ProtoMessage() {}

func (x *ApiKeyCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_apikey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyCreateRep.ProtoReflect.Descriptor instead.
func (*ApiKeyCreateRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_apikey_proto_rawDescGZIP(), []int{5}
}

func (x *ApiKeyCreateRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKeyCreateRep) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ApiKeyUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	McpOnly       *bool                  `protobuf:"varint,4,opt,name=mcp_only,json=mcpOnly,proto3,oneof" json:"mcp_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyUpdateReq) Reset() {
	*x = ApiKeyUpdateReq{}
	mi := &file_kusec_v1_apikey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyUpdateReq) ProtoMessage() {}

func (x *ApiKeyUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_apikey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyUpdateReq.ProtoReflect.Descriptor instead.
func (*ApiKeyUpdateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_apikey_proto_rawDescGZIP(), []int{6}
}

func (x *ApiKeyUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKeyUpdateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ApiKeyUpdateReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ApiKeyUpdateReq) GetMcpOnly() bool {
	if x != nil && x.McpOnly != nil {
		return *x.McpOnly
	}
	return false
}

var File_kusec_v1_apikey_proto protoreflect.FileDescriptor

const file_kusec_v1_apikey_proto_rawDesc = "" +
	"\n" +
	"\x15kusec_v1/apikey.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15kusec_v1/common.proto\"\xcd\x02\n" +
	"\n" +
	"ApiKeyMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x15\n" +
	"\x06usr_id\x18\x04 \x01(\x03R\x05usrId\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x19\n" +
	"\bmcp_only\x18\t \x01(\bR\amcpOnly\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\a \x01(\tR\tkeyPrefix\x12<\n" +
	"\flast_used_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\x97\x01\n" +
	"\rApiKeyListReq\x127\n" +
	"\vlist_params\x18\x01 \x01(\v2\x16.kusec_v1.ListParamsStR\n" +
	"listParams\x12\x1a\n" +
	"\x06usr_id\x18\x02 \x01(\x03H\x00R\x05usrId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01B\t\n" +
	"\a_usr_idB\t\n" +
	"\a_active\"\x84\x01\n" +
	"\rApiKeyListRep\x12C\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x1a.kusec_v1.PaginationInfoStR\x0epaginationInfo\x12.\n" +
	"\aresults\x18\x02 \x03(\v2\x14.kusec_v1.ApiKeyMainR\aresults\"\x1e\n" +
	"\fApiKeyGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x0fApiKeyCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\x06usr_id\x18\x02 \x01(\x03H\x00R\x05usrId\x88\x01\x01\x12\x19\n" +
	"\bmcp_only\x18\x03 \x01(\bR\amcpOnlyB\t\n" +
	"\a_usr_id\"3\n" +
	"\x0fApiKeyCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x98\x01\n" +
	"\x0fApiKeyUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1e\n" +
	"\bmcp_only\x18\x04 \x01(\bH\x02R\amcpOnly\x88\x01\x01B\t\n" +
	"\a_activeB\a\n" +
	"\x05_nameB\v\n" +
	"\t_mcp_only2\xd1\x02\n" +
	"\x06ApiKey\x12J\n" +
	"\x04List\x12\x17.kusec_v1.ApiKeyListReq\x1a\x17.kusec_v1.ApiKeyListRep\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/api-key\x12S\n" +
	"\x06Create\x12\x19.kusec_v1.ApiKeyCreateReq\x1a\x19.kusec_v1.ApiKeyCreateRep\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/api-key\x12U\n" +
	"\x06Update\x12\x19.kusec_v1.ApiKeyUpdateReq\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/api-key/{id}\x12O\n" +
	"\x06Delete\x12\x16.kusec_v1.ApiKeyGetReq\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/api-key/{id}B\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_apikey_proto_rawDescOnce sync.Once
	file_kusec_v1_apikey_proto_rawDescData []byte
)

func file_kusec_v1_apikey_proto_rawDescGZIP() []byte {
	file_kusec_v1_apikey_proto_rawDescOnce.Do(func() {
		file_kusec_v1_apikey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_apikey_proto_rawDesc), len(file_kusec_v1_apikey_proto_rawDesc)))
	})
	return file_kusec_v1_apikey_proto_rawDescData
}

var file_kusec_v1_apikey_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kusec_v1_apikey_proto_goTypes = []any{
	(*ApiKeyMain)(nil),            // 0: kusec_v1.ApiKeyMain
	(*ApiKeyListReq)(nil),         // 1: kusec_v1.ApiKeyListReq
	(*ApiKeyListRep)(nil),         // 2: kusec_v1.ApiKeyListRep
	(*ApiKeyGetReq)(nil),          // 3: kusec_v1.ApiKeyGetReq
	(*ApiKeyCreateReq)(nil),       // 4: kusec_v1.ApiKeyCreateReq
	(*ApiKeyCreateRep)(nil),       // 5: kusec_v1.ApiKeyCreateRep
	(*ApiKeyUpdateReq)(nil),       // 6: kusec_v1.ApiKeyUpdateReq
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*ListParamsSt)(nil),          // 8: kusec_v1.ListParamsSt
	(*PaginationInfoSt)(nil),      // 9: kusec_v1.PaginationInfoSt
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_kusec_v1_apikey_proto_depIdxs = []int32{
	7,  // 0: kusec_v1.ApiKeyMain.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: kusec_v1.ApiKeyMain.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 2: kusec_v1.ApiKeyMain.last_used_at:type_name -> google.protobuf.Timestamp
	8,  // 3: kusec_v1.ApiKeyListReq.list_params:type_name -> kusec_v1.ListParamsSt
	9,  // 4: kusec_v1.ApiKeyListRep.pagination_info:type_name -> kusec_v1.PaginationInfoSt
	0,  // 5: kusec_v1.ApiKeyListRep.results:type_name -> kusec_v1.ApiKeyMain
	1,  // 6: kusec_v1.ApiKey.List:input_type -> kusec_v1.ApiKeyListReq
	4,  // 7: kusec_v1.ApiKey.Create:input_type -> kusec_v1.ApiKeyCreateReq
	6,  // 8: kusec_v1.ApiKey.Update:input_type -> kusec_v1.ApiKeyUpdateReq
	3,  // 9: kusec_v1.ApiKey.Delete:input_type -> kusec_v1.ApiKeyGetReq
	2,  // 10: kusec_v1.ApiKey.List:output_type -> kusec_v1.ApiKeyListRep
	5,  // 11: kusec_v1.ApiKey.Create:output_type -> kusec_v1.ApiKeyCreateRep
	10, // 12: kusec_v1.ApiKey.Update:output_type -> google.protobuf.Empty
	10, // 13: kusec_v1.ApiKey.Delete:output_type -> google.protobuf.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kusec_v1_apikey_proto_init() }
func file_kusec_v1_apikey_proto_init() {
	if File_kusec_v1_apikey_proto != nil {
		return
	}
	file_kusec_v1_common_proto_init()
	file_kusec_v1_apikey_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_apikey_proto_msgTypes[4].OneofWrappers = []any{}
	file_kusec_v1_apikey_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_apikey_proto_rawDesc), len(file_kusec_v1_apikey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_apikey_proto_goTypes,
		DependencyIndexes: file_kusec_v1_apikey_proto_depIdxs,
		MessageInfos:      file_kusec_v1_apikey_proto_msgTypes,
	}.Build()
	File_kusec_v1_apikey_proto = out.File
	file_kusec_v1_apikey_proto_goTypes = nil
	file_kusec_v1_apikey_proto_depIdxs = nil
}
