// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: kusec_v1/apikey.proto

package kusec_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiKey_List_FullMethodName   = "/kusec_v1.ApiKey/List"
	ApiKey_Create_FullMethodName = "/kusec_v1.ApiKey/Create"
	ApiKey_Update_FullMethodName = "/kusec_v1.ApiKey/Update"
	ApiKey_Delete_FullMethodName = "/kusec_v1.ApiKey/Delete"
)

// ApiKeyClient is the client API for ApiKey service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApiKey — долгоживущие ключи для машинных клиентов (MCP-сервер, CI).
// Ключ наследует права владельца; хранится только хэш, значение ключа
// возвращается один раз при создании.
type ApiKeyClient interface {
	List(ctx context.Context, in *ApiKeyListReq, opts ...grpc.CallOption) (*ApiKeyListRep, error)
	Create(ctx context.Context, in *ApiKeyCreateReq, opts ...grpc.CallOption) (*ApiKeyCreateRep, error)
	Update(ctx context.Context, in *ApiKeyUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *ApiKeyGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type apiKeyClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeyClient(cc grpc.ClientConnInterface) ApiKeyClient {
	return &apiKeyClient{cc}
}

func (c *apiKeyClient) List(ctx context.Context, in *ApiKeyListReq, opts ...grpc.CallOption) (*ApiKeyListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyListRep)
	err := c.cc.Invoke(ctx, ApiKey_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyClient) Create(ctx context.Context, in *ApiKeyCreateReq, opts ...grpc.CallOption) (*ApiKeyCreateRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyCreateRep)
	err := c.cc.Invoke(ctx, ApiKey_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyClient) Update(ctx context.Context, in *ApiKeyUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiKey_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyClient) Delete(ctx context.Context, in *ApiKeyGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiKey_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeyServer is the server API for ApiKey service.
// All implementations must embed UnimplementedApiKeyServer
// for forward compatibility.
//
// ApiKey — долгоживущие ключи для машинных клиентов (MCP-сервер, CI).
// Ключ наследует права владельца; хранится только хэш, значение ключа
// возвращается один раз при создании.
type ApiKeyServer interface {
	List(context.Context, *ApiKeyListReq) (*ApiKeyListRep, error)
	Create(context.Context, *ApiKeyCreateReq) (*ApiKeyCreateRep, error)
	Update(context.Context, *ApiKeyUpdateReq) (*emptypb.Empty, error)
	Delete(context.Context, *ApiKeyGetReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedApiKeyServer()
}

// UnimplementedApiKeyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiKeyServer struct{}

func (UnimplementedApiKeyServer) List(context.Context, *ApiKeyListReq) (*ApiKeyListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedApiKeyServer) Create(context.Context, *ApiKeyCreateReq) (*ApiKeyCreateRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedApiKeyServer) Update(context.Context, *ApiKeyUpdateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedApiKeyServer) Delete(context.Context, *ApiKeyGetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedApiKeyServer) mustEmbedUnimplementedApiKeyServer() {}
func (UnimplementedApiKeyServer) testEmbeddedByValue()                {}

// UnsafeApiKeyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeyServer will
// result in compilation errors.
type UnsafeApiKeyServer interface {
	mustEmbedUnimplementedApiKeyServer()
}

func RegisterApiKeyServer(s grpc.ServiceRegistrar, srv ApiKeyServer) {
	// If the following call pancis, it indicates UnimplementedApiKeyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiKey_ServiceDesc, srv)
}

func _ApiKey_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiKeyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKey_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyServer).List(ctx, req.(*ApiKeyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKey_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiKeyCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKey_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyServer).Create(ctx, req.(*ApiKeyCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKey_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiKeyUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKey_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyServer).Update(ctx, req.(*ApiKeyUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKey_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiKeyGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKey_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyServer).Delete(ctx, req.(*ApiKeyGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKey_ServiceDesc is the grpc.ServiceDesc for ApiKey service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKey_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kusec_v1.ApiKey",
	HandlerType: (*ApiKeyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ApiKey_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ApiKey_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ApiKey_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ApiKey_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kusec_v1/apikey.proto",
}
