// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/app.proto

package kusec_v1

import (
	common "github.com/mechta-market/kusec/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppMain) Reset() {
	*x = AppMain{}
	mi := &file_kusec_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMain) ProtoMessage() {}

func (x *AppMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMain.ProtoReflect.Descriptor instead.
func (*AppMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppMain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AppMain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AppMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppMain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AppListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Search        *string                `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppListReq) Reset() {
	*x = AppListReq{}
	mi := &file_kusec_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListReq) ProtoMessage() {}

func (x *AppListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListReq.ProtoReflect.Descriptor instead.
func (*AppListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *AppListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *AppListReq) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type AppListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*AppMain               `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppListRep) Reset() {
	*x = AppListRep{}
	mi := &file_kusec_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListRep) ProtoMessage() {}

func (x *AppListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListRep.ProtoReflect.Descriptor instead.
func (*AppListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *AppListRep) GetResults() []*AppMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type AppGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGetReq) Reset() {
	*x = AppGetReq{}
	mi := &file_kusec_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGetReq) ProtoMessage() {}

func (x *AppGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGetReq.ProtoReflect.Descriptor instead.
func (*AppGetReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *AppGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AppCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        *bool                  `protobuf:"varint,1,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppCreateReq) Reset() {
	*x = AppCreateReq{}
	mi := &file_kusec_v1_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCreateReq) ProtoMessage() {}

func (x *AppCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCreateReq.ProtoReflect.Descriptor instead.
func (*AppCreateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *AppCreateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *AppCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AppCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppCreateRep) Reset() {
	*x = AppCreateRep{}
	mi := &file_kusec_v1_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCreateRep) ProtoMessage() {}

func (x *AppCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCreateRep.ProtoReflect.Descriptor instead.
func (*AppCreateRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_app_proto_rawDescGZIP(), []int{5}
}

func (x *AppCreateRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AppUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUpdateReq) Reset() {
	*x = AppUpdateReq{}
	mi := &file_kusec_v1_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUpdateReq) ProtoMessage() {}

func (x *AppUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUpdateReq.ProtoReflect.Descriptor instead.
func (*AppUpdateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_app_proto_rawDescGZIP(), []int{6}
}

func (x *AppUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppUpdateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *AppUpdateReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AppUpdateReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_kusec_v1_app_proto protoreflect.FileDescriptor

const file_kusec_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x12kusec_v1/app.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xdd\x01\n" +
	"\aAppMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x93\x01\n" +
	"\n" +
	"AppListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x01R\x06search\x88\x01\x01B\t\n" +
	"\a_activeB\t\n" +
	"\a_search\"|\n" +
	"\n" +
	"AppListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x12+\n" +
	"\aresults\x18\x02 \x03(\v2\x11.kusec_v1.AppMainR\aresults\"\x1b\n" +
	"\tAppGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"l\n" +
	"\fAppCreateReq\x12\x1b\n" +
	"\x06active\x18\x01 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB\t\n" +
	"\a_active\"\x1e\n" +
	"\fAppCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9f\x01\n" +
	"\fAppUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01B\t\n" +
	"\a_activeB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description2\xf3\x02\n" +
	"\x03App\x12A\n" +
	"\x04List\x12\x14.kusec_v1.AppListReq\x1a\x14.kusec_v1.AppListRep\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/apps\x12A\n" +
	"\x03Get\x12\x13.kusec_v1.AppGetReq\x1a\x11.kusec_v1.AppMain\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/apps/{id}\x12J\n" +
	"\x06Create\x12\x16.kusec_v1.AppCreateReq\x1a\x16.kusec_v1.AppCreateRep\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/apps\x12O\n" +
	"\x06Update\x12\x16.kusec_v1.AppUpdateReq\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*2\n" +
	"/apps/{id}\x12I\n" +
	"\x06Delete\x12\x13.kusec_v1.AppGetReq\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/apps/{id}B\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_app_proto_rawDescOnce sync.Once
	file_kusec_v1_app_proto_rawDescData []byte
)

func file_kusec_v1_app_proto_rawDescGZIP() []byte {
	file_kusec_v1_app_proto_rawDescOnce.Do(func() {
		file_kusec_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_app_proto_rawDesc), len(file_kusec_v1_app_proto_rawDesc)))
	})
	return file_kusec_v1_app_proto_rawDescData
}

var file_kusec_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kusec_v1_app_proto_goTypes = []any{
	(*AppMain)(nil),                 // 0: kusec_v1.AppMain
	(*AppListReq)(nil),              // 1: kusec_v1.AppListReq
	(*AppListRep)(nil),              // 2: kusec_v1.AppListRep
	(*AppGetReq)(nil),               // 3: kusec_v1.AppGetReq
	(*AppCreateReq)(nil),            // 4: kusec_v1.AppCreateReq
	(*AppCreateRep)(nil),            // 5: kusec_v1.AppCreateRep
	(*AppUpdateReq)(nil),            // 6: kusec_v1.AppUpdateReq
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 8: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 9: common.PaginationInfoSt
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_kusec_v1_app_proto_depIdxs = []int32{
	7,  // 0: kusec_v1.AppMain.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: kusec_v1.AppMain.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: kusec_v1.AppListReq.list_params:type_name -> common.ListParamsSt
	9,  // 3: kusec_v1.AppListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 4: kusec_v1.AppListRep.results:type_name -> kusec_v1.AppMain
	1,  // 5: kusec_v1.App.List:input_type -> kusec_v1.AppListReq
	3,  // 6: kusec_v1.App.Get:input_type -> kusec_v1.AppGetReq
	4,  // 7: kusec_v1.App.Create:input_type -> kusec_v1.AppCreateReq
	6,  // 8: kusec_v1.App.Update:input_type -> kusec_v1.AppUpdateReq
	3,  // 9: kusec_v1.App.Delete:input_type -> kusec_v1.AppGetReq
	2,  // 10: kusec_v1.App.List:output_type -> kusec_v1.AppListRep
	0,  // 11: kusec_v1.App.Get:output_type -> kusec_v1.AppMain
	5,  // 12: kusec_v1.App.Create:output_type -> kusec_v1.AppCreateRep
	10, // 13: kusec_v1.App.Update:output_type -> google.protobuf.Empty
	10, // 14: kusec_v1.App.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_kusec_v1_app_proto_init() }
func file_kusec_v1_app_proto_init() {
	if File_kusec_v1_app_proto != nil {
		return
	}
	file_kusec_v1_app_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_app_proto_msgTypes[4].OneofWrappers = []any{}
	file_kusec_v1_app_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_app_proto_rawDesc), len(file_kusec_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_app_proto_goTypes,
		DependencyIndexes: file_kusec_v1_app_proto_depIdxs,
		MessageInfos:      file_kusec_v1_app_proto_msgTypes,
	}.Build()
	File_kusec_v1_app_proto = out.File
	file_kusec_v1_app_proto_goTypes = nil
	file_kusec_v1_app_proto_depIdxs = nil
}
