// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/audit.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Одно изменённое поле. Для несекретных полей — old/new как есть (null —
// стороны нет: create/delete). Для значений item (secret) и усечённых больших
// значений config_item — только отпечаток (old_hash/new_hash, HMAC-SHA256,
// 16 hex) и размер в байтах.
type AuditChangeSt struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Field   string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Old     *string                `protobuf:"bytes,2,opt,name=old,proto3,oneof" json:"old,omitempty"`
	New     *string                `protobuf:"bytes,3,opt,name=new,proto3,oneof" json:"new,omitempty"`
	OldHash string                 `protobuf:"bytes,4,opt,name=old_hash,json=oldHash,proto3" json:"old_hash,omitempty"`
	NewHash string                 `protobuf:"bytes,5,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	OldSize *int64                 `protobuf:"varint,6,opt,name=old_size,json=oldSize,proto3,oneof" json:"old_size,omitempty"`
	NewSize *int64                 `protobuf:"varint,7,opt,name=new_size,json=newSize,proto3,oneof" json:"new_size,omitempty"`
	// Несекретное значение длиннее лимита — сохранён только отпечаток.
	Truncated     bool `protobuf:"varint,8,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditChangeSt) Reset() {
	*x = AuditChangeSt{}
	mi := &file_kusec_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditChangeSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditChangeSt) ProtoMessage() {}

func (x *AuditChangeSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditChangeSt.ProtoReflect.Descriptor instead.
func (*AuditChangeSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditChangeSt) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AuditChangeSt) GetOld() string {
	if x != nil && x.Old != nil {
		return *x.Old
	}
	return ""
}

func (x *AuditChangeSt) GetNew() string {
	if x != nil && x.New != nil {
		return *x.New
	}
	return ""
}

func (x *AuditChangeSt) GetOldHash() string {
	if x != nil {
		return x.OldHash
	}
	return ""
}

func (x *AuditChangeSt) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

func (x *AuditChangeSt) GetOldSize() int64 {
	if x != nil && x.OldSize != nil {
		return *x.OldSize
	}
	return 0
}

func (x *AuditChangeSt) GetNewSize() int64 {
	if x != nil && x.NewSize != nil {
		return *x.NewSize
	}
	return 0
}

func (x *AuditChangeSt) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type AuditMain struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// actor: имя денормализовано (пользователь или ключ могут быть удалены)
	ActorUsrId    *int64  `protobuf:"varint,3,opt,name=actor_usr_id,json=actorUsrId,proto3,oneof" json:"actor_usr_id,omitempty"`
	ActorApiKeyId *string `protobuf:"bytes,4,opt,name=actor_api_key_id,json=actorApiKeyId,proto3,oneof" json:"actor_api_key_id,omitempty"`
	ActorName     string  `protobuf:"bytes,5,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	// ui | api | mcp | system
	Source    string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// app | secret | item | configmap | config_item | api_key | usr | sync_run
	EntityType string  `protobuf:"bytes,8,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId   string  `protobuf:"bytes,9,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	AppId      *string `protobuf:"bytes,10,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	Namespace  string  `protobuf:"bytes,11,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AppSlug    string  `protobuf:"bytes,12,opt,name=app_slug,json=appSlug,proto3" json:"app_slug,omitempty"`
	// Secret | ConfigMap | ""
	KubeKind string `protobuf:"bytes,13,opt,name=kube_kind,json=kubeKind,proto3" json:"kube_kind,omitempty"`
	// итоговое имя k8s-объекта
	KubeName string `protobuf:"bytes,14,opt,name=kube_name,json=kubeName,proto3" json:"kube_name,omitempty"`
	// ключ item/config_item
	Key string `protobuf:"bytes,15,opt,name=key,proto3" json:"key,omitempty"`
	// create | update | delete | activate | deactivate | sync | import
	Action  string           `protobuf:"bytes,16,opt,name=action,proto3" json:"action,omitempty"`
	Changes []*AuditChangeSt `protobuf:"bytes,17,rep,name=changes,proto3" json:"changes,omitempty"`
	// группировка массовых операций (каскадное удаление, импорт, sync)
	BatchId       *string `protobuf:"bytes,18,opt,name=batch_id,json=batchId,proto3,oneof" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditMain) Reset() {
	*x = AuditMain{}
	mi := &file_kusec_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditMain) ProtoMessage() {}

func (x *AuditMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditMain.ProtoReflect.Descriptor instead.
func (*AuditMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditMain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditMain) GetActorUsrId() int64 {
	if x != nil && x.ActorUsrId != nil {
		return *x.ActorUsrId
	}
	return 0
}

func (x *AuditMain) GetActorApiKeyId() string {
	if x != nil && x.ActorApiKeyId != nil {
		return *x.ActorApiKeyId
	}
	return ""
}

func (x *AuditMain) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *AuditMain) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuditMain) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditMain) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditMain) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditMain) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *AuditMain) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AuditMain) GetAppSlug() string {
	if x != nil {
		return x.AppSlug
	}
	return ""
}

func (x *AuditMain) GetKubeKind() string {
	if x != nil {
		return x.KubeKind
	}
	return ""
}

func (x *AuditMain) GetKubeName() string {
	if x != nil {
		return x.KubeName
	}
	return ""
}

func (x *AuditMain) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuditMain) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditMain) GetChanges() []*AuditChangeSt {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *AuditMain) GetBatchId() string {
	if x != nil && x.BatchId != nil {
		return *x.BatchId
	}
	return ""
}

type AuditListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page с 0, page_size обязателен (≤ 100); сортировка по умолчанию
	// -created_at (новые первыми).
	ListParams *ListParamsSt `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	AppId      *string       `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	Namespace  *string       `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	AppSlug    *string       `protobuf:"bytes,4,opt,name=app_slug,json=appSlug,proto3,oneof" json:"app_slug,omitempty"`
	KubeName   *string       `protobuf:"bytes,5,opt,name=kube_name,json=kubeName,proto3,oneof" json:"kube_name,omitempty"`
	EntityType *string       `protobuf:"bytes,6,opt,name=entity_type,json=entityType,proto3,oneof" json:"entity_type,omitempty"`
	EntityId   *string       `protobuf:"bytes,7,opt,name=entity_id,json=entityId,proto3,oneof" json:"entity_id,omitempty"`
	Action     *string       `protobuf:"bytes,8,opt,name=action,proto3,oneof" json:"action,omitempty"`
	ActorUsrId *int64        `protobuf:"varint,9,opt,name=actor_usr_id,json=actorUsrId,proto3,oneof" json:"actor_usr_id,omitempty"`
	Key        *string       `protobuf:"bytes,10,opt,name=key,proto3,oneof" json:"key,omitempty"`
	BatchId    *string       `protobuf:"bytes,11,opt,name=batch_id,json=batchId,proto3,oneof" json:"batch_id,omitempty"`
	// Границы по времени изменения (RFC3339): created_at >= gte, < lt.
	CreatedAtGte  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at_gte,json=createdAtGte,proto3,oneof" json:"created_at_gte,omitempty"`
	CreatedAtLt   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at_lt,json=createdAtLt,proto3,oneof" json:"created_at_lt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditListReq) Reset() {
	*x = AuditListReq{}
	mi := &file_kusec_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditListReq) ProtoMessage() {}

func (x *AuditListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditListReq.ProtoReflect.Descriptor instead.
func (*AuditListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *AuditListReq) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *AuditListReq) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *AuditListReq) GetAppSlug() string {
	if x != nil && x.AppSlug != nil {
		return *x.AppSlug
	}
	return ""
}

func (x *AuditListReq) GetKubeName() string {
	if x != nil && x.KubeName != nil {
		return *x.KubeName
	}
	return ""
}

func (x *AuditListReq) GetEntityType() string {
	if x != nil && x.EntityType != nil {
		return *x.EntityType
	}
	return ""
}

func (x *AuditListReq) GetEntityId() string {
	if x != nil && x.EntityId != nil {
		return *x.EntityId
	}
	return ""
}

func (x *AuditListReq) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *AuditListReq) GetActorUsrId() int64 {
	if x != nil && x.ActorUsrId != nil {
		return *x.ActorUsrId
	}
	return 0
}

func (x *AuditListReq) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *AuditListReq) GetBatchId() string {
	if x != nil && x.BatchId != nil {
		return *x.BatchId
	}
	return ""
}

func (x *AuditListReq) GetCreatedAtGte() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtGte
	}
	return nil
}

func (x *AuditListReq) GetCreatedAtLt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtLt
	}
	return nil
}

type AuditListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*AuditMain           `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditListRep) Reset() {
	*x = AuditListRep{}
	mi := &file_kusec_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditListRep) ProtoMessage() {}

func (x *AuditListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditListRep.ProtoReflect.Descriptor instead.
func (*AuditListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *AuditListRep) GetResults() []*AuditMain {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_kusec_v1_audit_proto protoreflect.FileDescriptor

const file_kusec_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x14kusec_v1/audit.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15kusec_v1/common.proto\"\x91\x02\n" +
	"\rAuditChangeSt\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x15\n" +
	"\x03old\x18\x02 \x01(\tH\x00R\x03old\x88\x01\x01\x12\x15\n" +
	"\x03new\x18\x03 \x01(\tH\x01R\x03new\x88\x01\x01\x12\x19\n" +
	"\bold_hash\x18\x04 \x01(\tR\aoldHash\x12\x19\n" +
	"\bnew_hash\x18\x05 \x01(\tR\anewHash\x12\x1e\n" +
	"\bold_size\x18\x06 \x01(\x03H\x02R\aoldSize\x88\x01\x01\x12\x1e\n" +
	"\bnew_size\x18\a \x01(\x03H\x03R\anewSize\x88\x01\x01\x12\x1c\n" +
	"\ttruncated\x18\b \x01(\bR\ttruncatedB\x06\n" +
	"\x04_oldB\x06\n" +
	"\x04_newB\v\n" +
	"\t_old_sizeB\v\n" +
	"\t_new_size\"\x89\x05\n" +
	"\tAuditMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\factor_usr_id\x18\x03 \x01(\x03H\x00R\n" +
	"actorUsrId\x88\x01\x01\x12,\n" +
	"\x10actor_api_key_id\x18\x04 \x01(\tH\x01R\ractorApiKeyId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x05 \x01(\tR\tactorName\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x1f\n" +
	"\ventity_type\x18\b \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\t \x01(\tR\bentityId\x12\x1a\n" +
	"\x06app_id\x18\n" +
	" \x01(\tH\x02R\x05appId\x88\x01\x01\x12\x1c\n" +
	"\tnamespace\x18\v \x01(\tR\tnamespace\x12\x19\n" +
	"\bapp_slug\x18\f \x01(\tR\aappSlug\x12\x1b\n" +
	"\tkube_kind\x18\r \x01(\tR\bkubeKind\x12\x1b\n" +
	"\tkube_name\x18\x0e \x01(\tR\bkubeName\x12\x10\n" +
	"\x03key\x18\x0f \x01(\tR\x03key\x12\x16\n" +
	"\x06action\x18\x10 \x01(\tR\x06action\x121\n" +
	"\achanges\x18\x11 \x03(\v2\x17.kusec_v1.AuditChangeStR\achanges\x12\x1e\n" +
	"\bbatch_id\x18\x12 \x01(\tH\x03R\abatchId\x88\x01\x01B\x0f\n" +
	"\r_actor_usr_idB\x13\n" +
	"\x11_actor_api_key_idB\t\n" +
	"\a_app_idB\v\n" +
	"\t_batch_id\"\xbf\x05\n" +
	"\fAuditListReq\x127\n" +
	"\vlist_params\x18\x01 \x01(\v2\x16.kusec_v1.ListParamsStR\n" +
	"listParams\x12\x1a\n" +
	"\x06app_id\x18\x02 \x01(\tH\x00R\x05appId\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x01R\tnamespace\x88\x01\x01\x12\x1e\n" +
	"\bapp_slug\x18\x04 \x01(\tH\x02R\aappSlug\x88\x01\x01\x12 \n" +
	"\tkube_name\x18\x05 \x01(\tH\x03R\bkubeName\x88\x01\x01\x12$\n" +
	"\ventity_type\x18\x06 \x01(\tH\x04R\n" +
	"entityType\x88\x01\x01\x12 \n" +
	"\tentity_id\x18\a \x01(\tH\x05R\bentityId\x88\x01\x01\x12\x1b\n" +
	"\x06action\x18\b \x01(\tH\x06R\x06action\x88\x01\x01\x12%\n" +
	"\factor_usr_id\x18\t \x01(\x03H\aR\n" +
	"actorUsrId\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\n" +
	" \x01(\tH\bR\x03key\x88\x01\x01\x12\x1e\n" +
	"\bbatch_id\x18\v \x01(\tH\tR\abatchId\x88\x01\x01\x12E\n" +
	"\x0ecreated_at_gte\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\n" +
	"R\fcreatedAtGte\x88\x01\x01\x12C\n" +
	"\rcreated_at_lt\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\vR\vcreatedAtLt\x88\x01\x01B\t\n" +
	"\a_app_idB\f\n" +
	"\n" +
	"_namespaceB\v\n" +
	"\t_app_slugB\f\n" +
	"\n" +
	"_kube_nameB\x0e\n" +
	"\f_entity_typeB\f\n" +
	"\n" +
	"_entity_idB\t\n" +
	"\a_actionB\x0f\n" +
	"\r_actor_usr_idB\x06\n" +
	"\x04_keyB\v\n" +
	"\t_batch_idB\x11\n" +
	"\x0f_created_at_gteB\x10\n" +
	"\x0e_created_at_lt\"\x82\x01\n" +
	"\fAuditListRep\x12C\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x1a.kusec_v1.PaginationInfoStR\x0epaginationInfo\x12-\n" +
	"\aresults\x18\x02 \x03(\v2\x13.kusec_v1.AuditMainR\aresults2O\n" +
	"\x05Audit\x12F\n" +
	"\x04List\x12\x16.kusec_v1.AuditListReq\x1a\x16.kusec_v1.AuditListRep\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/auditB\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_audit_proto_rawDescOnce sync.Once
	file_kusec_v1_audit_proto_rawDescData []byte
)

func file_kusec_v1_audit_proto_rawDescGZIP() []byte {
	file_kusec_v1_audit_proto_rawDescOnce.Do(func() {
		file_kusec_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_audit_proto_rawDesc), len(file_kusec_v1_audit_proto_rawDesc)))
	})
	return file_kusec_v1_audit_proto_rawDescData
}

var file_kusec_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kusec_v1_audit_proto_goTypes = []any{
	(*AuditChangeSt)(nil),         // 0: kusec_v1.AuditChangeSt
	(*AuditMain)(nil),             // 1: kusec_v1.AuditMain
	(*AuditListReq)(nil),          // 2: kusec_v1.AuditListReq
	(*AuditListRep)(nil),          // 3: kusec_v1.AuditListRep
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*ListParamsSt)(nil),          // 5: kusec_v1.ListParamsSt
	(*PaginationInfoSt)(nil),      // 6: kusec_v1.PaginationInfoSt
}
var file_kusec_v1_audit_proto_depIdxs = []int32{
	4, // 0: kusec_v1.AuditMain.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: kusec_v1.AuditMain.changes:type_name -> kusec_v1.AuditChangeSt
	5, // 2: kusec_v1.AuditListReq.list_params:type_name -> kusec_v1.ListParamsSt
	4, // 3: kusec_v1.AuditListReq.created_at_gte:type_name -> google.protobuf.Timestamp
	4, // 4: kusec_v1.AuditListReq.created_at_lt:type_name -> google.protobuf.Timestamp
	6, // 5: kusec_v1.AuditListRep.pagination_info:type_name -> kusec_v1.PaginationInfoSt
	1, // 6: kusec_v1.AuditListRep.results:type_name -> kusec_v1.AuditMain
	2, // 7: kusec_v1.Audit.List:input_type -> kusec_v1.AuditListReq
	3, // 8: kusec_v1.Audit.List:output_type -> kusec_v1.AuditListRep
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_kusec_v1_audit_proto_init() }
func file_kusec_v1_audit_proto_init() {
	if File_kusec_v1_audit_proto != nil {
		return
	}
	file_kusec_v1_common_proto_init()
	file_kusec_v1_audit_proto_msgTypes[0].OneofWrappers = []any{}
	file_kusec_v1_audit_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_audit_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_audit_proto_rawDesc), len(file_kusec_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_audit_proto_goTypes,
		DependencyIndexes: file_kusec_v1_audit_proto_depIdxs,
		MessageInfos:      file_kusec_v1_audit_proto_msgTypes,
	}.Build()
	File_kusec_v1_audit_proto = out.File
	file_kusec_v1_audit_proto_goTypes = nil
	file_kusec_v1_audit_proto_depIdxs = nil
}
