// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/configitem.proto

package kusec_v1

import (
	common "github.com/mechta-market/kusec/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigItemMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ConfigmapId   string                 `protobuf:"bytes,4,opt,name=configmap_id,json=configmapId,proto3" json:"configmap_id,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	ValueFormat   string                 `protobuf:"bytes,9,opt,name=value_format,json=valueFormat,proto3" json:"value_format,omitempty"`
	Encoding      string                 `protobuf:"bytes,10,opt,name=encoding,proto3" json:"encoding,omitempty"`
	FileName      string                 `protobuf:"bytes,11,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,12,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemMain) Reset() {
	*x = ConfigItemMain{}
	mi := &file_kusec_v1_configitem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemMain) ProtoMessage() {}

func (x *ConfigItemMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configitem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemMain.ProtoReflect.Descriptor instead.
func (*ConfigItemMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configitem_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigItemMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigItemMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigItemMain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfigItemMain) GetConfigmapId() string {
	if x != nil {
		return x.ConfigmapId
	}
	return ""
}

func (x *ConfigItemMain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ConfigItemMain) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItemMain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigItemMain) GetValueFormat() string {
	if x != nil {
		return x.ValueFormat
	}
	return ""
}

func (x *ConfigItemMain) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *ConfigItemMain) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ConfigItemMain) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigItemMain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigItemListReq struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ListParams  *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	ConfigmapId *string                `protobuf:"bytes,2,opt,name=configmap_id,json=configmapId,proto3,oneof" json:"configmap_id,omitempty"`
	Active      *bool                  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Search      *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	// Выборка по нескольким configmap-ам за один запрос (без пагинации).
	ConfigmapIds  []string `protobuf:"bytes,5,rep,name=configmap_ids,json=configmapIds,proto3" json:"configmap_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemListReq) Reset() {
	*x = ConfigItemListReq{}
	mi := &file_kusec_v1_configitem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemListReq) ProtoMessage() {}

func (x *ConfigItemListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configitem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemListReq.ProtoReflect.Descriptor instead.
func (*ConfigItemListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configitem_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigItemListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *ConfigItemListReq) GetConfigmapId() string {
	if x != nil && x.ConfigmapId != nil {
		return *x.ConfigmapId
	}
	return ""
}

func (x *ConfigItemListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ConfigItemListReq) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ConfigItemListReq) GetConfigmapIds() []string {
	if x != nil {
		return x.ConfigmapIds
	}
	return nil
}

type ConfigItemListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*ConfigItemMain        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigItemListRep) Reset() {
	*x = ConfigItemListRep{}
	mi := &file_kusec_v1_configitem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemListRep) ProtoMessage() {}

func (x *ConfigItemListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configitem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemListRep.ProtoReflect.Descriptor instead.
func (*ConfigItemListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configitem_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigItemListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *ConfigItemListRep) GetResults() []*ConfigItemMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type ConfigItemGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemGetReq) Reset() {
	*x = ConfigItemGetReq{}
	mi := &file_kusec_v1_configitem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemGetReq) ProtoMessage() {}

func (x *ConfigItemGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configitem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemGetReq.ProtoReflect.Descriptor instead.
func (*ConfigItemGetReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configitem_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigItemGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfigItemCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigmapId   string                 `protobuf:"bytes,1,opt,name=configmap_id,json=configmapId,proto3" json:"configmap_id,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueFormat   *string                `protobuf:"bytes,6,opt,name=value_format,json=valueFormat,proto3,oneof" json:"value_format,omitempty"`
	Encoding      *string                `protobuf:"bytes,7,opt,name=encoding,proto3,oneof" json:"encoding,omitempty"`
	FileName      *string                `protobuf:"bytes,8,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	ContentType   *string                `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemCreateReq) Reset() {
	*x = ConfigItemCreateReq{}
	mi := &file_kusec_v1_configitem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemCreateReq) ProtoMessage() {}

func (x *ConfigItemCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configitem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemCreateReq.ProtoReflect.Descriptor instead.
func (*ConfigItemCreateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configitem_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigItemCreateReq) GetConfigmapId() string {
	if x != nil {
		return x.ConfigmapId
	}
	return ""
}

func (x *ConfigItemCreateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ConfigItemCreateReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItemCreateReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigItemCreateReq) GetValueFormat() string {
	if x != nil && x.ValueFormat != nil {
		return *x.ValueFormat
	}
	return ""
}

func (x *ConfigItemCreateReq) GetEncoding() string {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return ""
}

func (x *ConfigItemCreateReq) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *ConfigItemCreateReq) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *ConfigItemCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigItemCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemCreateRep) Reset() {
	*x = ConfigItemCreateRep{}
	mi := &file_kusec_v1_configitem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemCreateRep) ProtoMessage() {}

func (x *ConfigItemCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configitem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemCreateRep.ProtoReflect.Descriptor instead.
func (*ConfigItemCreateRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configitem_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigItemCreateRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfigItemUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigmapId   *string                `protobuf:"bytes,2,opt,name=configmap_id,json=configmapId,proto3,oneof" json:"configmap_id,omitempty"`
	Active        *bool                  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Key           *string                `protobuf:"bytes,4,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,5,opt,name=value,proto3,oneof" json:"value,omitempty"`
	ValueFormat   *string                `protobuf:"bytes,7,opt,name=value_format,json=valueFormat,proto3,oneof" json:"value_format,omitempty"`
	Encoding      *string                `protobuf:"bytes,8,opt,name=encoding,proto3,oneof" json:"encoding,omitempty"`
	FileName      *string                `protobuf:"bytes,9,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	ContentType   *string                `protobuf:"bytes,10,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemUpdateReq) Reset() {
	*x = ConfigItemUpdateReq{}
	mi := &file_kusec_v1_configitem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemUpdateReq) ProtoMessage() {}

func (x *ConfigItemUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configitem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemUpdateReq.ProtoReflect.Descriptor instead.
func (*ConfigItemUpdateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configitem_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigItemUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetConfigmapId() string {
	if x != nil && x.ConfigmapId != nil {
		return *x.ConfigmapId
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ConfigItemUpdateReq) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetValueFormat() string {
	if x != nil && x.ValueFormat != nil {
		return *x.ValueFormat
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetEncoding() string {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *ConfigItemUpdateReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_kusec_v1_configitem_proto protoreflect.FileDescriptor

const file_kusec_v1_configitem_proto_rawDesc = "" +
	"\n" +
	"\x19kusec_v1/configitem.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x9a\x03\n" +
	"\x0eConfigItemMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\fconfigmap_id\x18\x04 \x01(\tR\vconfigmapId\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12!\n" +
	"\fvalue_format\x18\t \x01(\tR\vvalueFormat\x12\x1a\n" +
	"\bencoding\x18\n" +
	" \x01(\tR\bencoding\x12\x1b\n" +
	"\tfile_name\x18\v \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\f \x01(\tR\vcontentType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xf8\x01\n" +
	"\x11ConfigItemListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12&\n" +
	"\fconfigmap_id\x18\x02 \x01(\tH\x00R\vconfigmapId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x02R\x06search\x88\x01\x01\x12#\n" +
	"\rconfigmap_ids\x18\x05 \x03(\tR\fconfigmapIdsB\x0f\n" +
	"\r_configmap_idB\t\n" +
	"\a_activeB\t\n" +
	"\a_search\"\x8a\x01\n" +
	"\x11ConfigItemListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x122\n" +
	"\aresults\x18\x02 \x03(\v2\x18.kusec_v1.ConfigItemMainR\aresults\"\"\n" +
	"\x10ConfigItemGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xfa\x02\n" +
	"\x13ConfigItemCreateReq\x12!\n" +
	"\fconfigmap_id\x18\x01 \x01(\tR\vconfigmapId\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12&\n" +
	"\fvalue_format\x18\x06 \x01(\tH\x01R\vvalueFormat\x88\x01\x01\x12\x1f\n" +
	"\bencoding\x18\a \x01(\tH\x02R\bencoding\x88\x01\x01\x12 \n" +
	"\tfile_name\x18\b \x01(\tH\x03R\bfileName\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\t \x01(\tH\x04R\vcontentType\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescriptionB\t\n" +
	"\a_activeB\x0f\n" +
	"\r_value_formatB\v\n" +
	"\t_encodingB\f\n" +
	"\n" +
	"_file_nameB\x0f\n" +
	"\r_content_type\"%\n" +
	"\x13ConfigItemCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd1\x03\n" +
	"\x13ConfigItemUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\fconfigmap_id\x18\x02 \x01(\tH\x00R\vconfigmapId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x04 \x01(\tH\x02R\x03key\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x05 \x01(\tH\x03R\x05value\x88\x01\x01\x12&\n" +
	"\fvalue_format\x18\a \x01(\tH\x04R\vvalueFormat\x88\x01\x01\x12\x1f\n" +
	"\bencoding\x18\b \x01(\tH\x05R\bencoding\x88\x01\x01\x12 \n" +
	"\tfile_name\x18\t \x01(\tH\x06R\bfileName\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\n" +
	" \x01(\tH\aR\vcontentType\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\bR\vdescription\x88\x01\x01B\x0f\n" +
	"\r_configmap_idB\t\n" +
	"\a_activeB\x06\n" +
	"\x04_keyB\b\n" +
	"\x06_valueB\x0f\n" +
	"\r_value_formatB\v\n" +
	"\t_encodingB\f\n" +
	"\n" +
	"_file_nameB\x0f\n" +
	"\r_content_typeB\x0e\n" +
	"\f_description2\xd5\x03\n" +
	"\n" +
	"ConfigItem\x12V\n" +
	"\x04List\x12\x1b.kusec_v1.ConfigItemListReq\x1a\x1b.kusec_v1.ConfigItemListRep\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/config-item\x12V\n" +
	"\x03Get\x12\x1a.kusec_v1.ConfigItemGetReq\x1a\x18.kusec_v1.ConfigItemMain\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/config-item/{id}\x12_\n" +
	"\x06Create\x12\x1d.kusec_v1.ConfigItemCreateReq\x1a\x1d.kusec_v1.ConfigItemCreateRep\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/config-item\x12]\n" +
	"\x06Update\x12\x1d.kusec_v1.ConfigItemUpdateReq\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/config-item/{id}\x12W\n" +
	"\x06Delete\x12\x1a.kusec_v1.ConfigItemGetReq\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/config-item/{id}B\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_configitem_proto_rawDescOnce sync.Once
	file_kusec_v1_configitem_proto_rawDescData []byte
)

func file_kusec_v1_configitem_proto_rawDescGZIP() []byte {
	file_kusec_v1_configitem_proto_rawDescOnce.Do(func() {
		file_kusec_v1_configitem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_configitem_proto_rawDesc), len(file_kusec_v1_configitem_proto_rawDesc)))
	})
	return file_kusec_v1_configitem_proto_rawDescData
}

var file_kusec_v1_configitem_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kusec_v1_configitem_proto_goTypes = []any{
	(*ConfigItemMain)(nil),          // 0: kusec_v1.ConfigItemMain
	(*ConfigItemListReq)(nil),       // 1: kusec_v1.ConfigItemListReq
	(*ConfigItemListRep)(nil),       // 2: kusec_v1.ConfigItemListRep
	(*ConfigItemGetReq)(nil),        // 3: kusec_v1.ConfigItemGetReq
	(*ConfigItemCreateReq)(nil),     // 4: kusec_v1.ConfigItemCreateReq
	(*ConfigItemCreateRep)(nil),     // 5: kusec_v1.ConfigItemCreateRep
	(*ConfigItemUpdateReq)(nil),     // 6: kusec_v1.ConfigItemUpdateReq
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 8: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 9: common.PaginationInfoSt
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_kusec_v1_configitem_proto_depIdxs = []int32{
	7,  // 0: kusec_v1.ConfigItemMain.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: kusec_v1.ConfigItemMain.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: kusec_v1.ConfigItemListReq.list_params:type_name -> common.ListParamsSt
	9,  // 3: kusec_v1.ConfigItemListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 4: kusec_v1.ConfigItemListRep.results:type_name -> kusec_v1.ConfigItemMain
	1,  // 5: kusec_v1.ConfigItem.List:input_type -> kusec_v1.ConfigItemListReq
	3,  // 6: kusec_v1.ConfigItem.Get:input_type -> kusec_v1.ConfigItemGetReq
	4,  // 7: kusec_v1.ConfigItem.Create:input_type -> kusec_v1.ConfigItemCreateReq
	6,  // 8: kusec_v1.ConfigItem.Update:input_type -> kusec_v1.ConfigItemUpdateReq
	3,  // 9: kusec_v1.ConfigItem.Delete:input_type -> kusec_v1.ConfigItemGetReq
	2,  // 10: kusec_v1.ConfigItem.List:output_type -> kusec_v1.ConfigItemListRep
	0,  // 11: kusec_v1.ConfigItem.Get:output_type -> kusec_v1.ConfigItemMain
	5,  // 12: kusec_v1.ConfigItem.Create:output_type -> kusec_v1.ConfigItemCreateRep
	10, // 13: kusec_v1.ConfigItem.Update:output_type -> google.protobuf.Empty
	10, // 14: kusec_v1.ConfigItem.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_kusec_v1_configitem_proto_init() }
func file_kusec_v1_configitem_proto_init() {
	if File_kusec_v1_configitem_proto != nil {
		return
	}
	file_kusec_v1_configitem_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_configitem_proto_msgTypes[4].OneofWrappers = []any{}
	file_kusec_v1_configitem_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_configitem_proto_rawDesc), len(file_kusec_v1_configitem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_configitem_proto_goTypes,
		DependencyIndexes: file_kusec_v1_configitem_proto_depIdxs,
		MessageInfos:      file_kusec_v1_configitem_proto_msgTypes,
	}.Build()
	File_kusec_v1_configitem_proto = out.File
	file_kusec_v1_configitem_proto_goTypes = nil
	file_kusec_v1_configitem_proto_depIdxs = nil
}
