// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: kusec_v1/configmap.proto

package kusec_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigMap_List_FullMethodName   = "/kusec_v1.ConfigMap/List"
	ConfigMap_Get_FullMethodName    = "/kusec_v1.ConfigMap/Get"
	ConfigMap_Create_FullMethodName = "/kusec_v1.ConfigMap/Create"
	ConfigMap_Update_FullMethodName = "/kusec_v1.ConfigMap/Update"
	ConfigMap_Delete_FullMethodName = "/kusec_v1.ConfigMap/Delete"
)

// ConfigMapClient is the client API for ConfigMap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigMapClient interface {
	List(ctx context.Context, in *ConfigMapListReq, opts ...grpc.CallOption) (*ConfigMapListRep, error)
	Get(ctx context.Context, in *ConfigMapGetReq, opts ...grpc.CallOption) (*ConfigMapMain, error)
	Create(ctx context.Context, in *ConfigMapCreateReq, opts ...grpc.CallOption) (*ConfigMapCreateRep, error)
	Update(ctx context.Context, in *ConfigMapUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *ConfigMapGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type configMapClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigMapClient(cc grpc.ClientConnInterface) ConfigMapClient {
	return &configMapClient{cc}
}

func (c *configMapClient) List(ctx context.Context, in *ConfigMapListReq, opts ...grpc.CallOption) (*ConfigMapListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMapListRep)
	err := c.cc.Invoke(ctx, ConfigMap_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configMapClient) Get(ctx context.Context, in *ConfigMapGetReq, opts ...grpc.CallOption) (*ConfigMapMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMapMain)
	err := c.cc.Invoke(ctx, ConfigMap_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configMapClient) Create(ctx context.Context, in *ConfigMapCreateReq, opts ...grpc.CallOption) (*ConfigMapCreateRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMapCreateRep)
	err := c.cc.Invoke(ctx, ConfigMap_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configMapClient) Update(ctx context.Context, in *ConfigMapUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConfigMap_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configMapClient) Delete(ctx context.Context, in *ConfigMapGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConfigMap_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigMapServer is the server API for ConfigMap service.
// All implementations must embed UnimplementedConfigMapServer
// for forward compatibility.
type ConfigMapServer interface {
	List(context.Context, *ConfigMapListReq) (*ConfigMapListRep, error)
	Get(context.Context, *ConfigMapGetReq) (*ConfigMapMain, error)
	Create(context.Context, *ConfigMapCreateReq) (*ConfigMapCreateRep, error)
	Update(context.Context, *ConfigMapUpdateReq) (*emptypb.Empty, error)
	Delete(context.Context, *ConfigMapGetReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedConfigMapServer()
}

// UnimplementedConfigMapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigMapServer struct{}

func (UnimplementedConfigMapServer) List(context.Context, *ConfigMapListReq) (*ConfigMapListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConfigMapServer) Get(context.Context, *ConfigMapGetReq) (*ConfigMapMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConfigMapServer) Create(context.Context, *ConfigMapCreateReq) (*ConfigMapCreateRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedConfigMapServer) Update(context.Context, *ConfigMapUpdateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedConfigMapServer) Delete(context.Context, *ConfigMapGetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConfigMapServer) mustEmbedUnimplementedConfigMapServer() {}
func (UnimplementedConfigMapServer) testEmbeddedByValue()                   {}

// UnsafeConfigMapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigMapServer will
// result in compilation errors.
type UnsafeConfigMapServer interface {
	mustEmbedUnimplementedConfigMapServer()
}

func RegisterConfigMapServer(s grpc.ServiceRegistrar, srv ConfigMapServer) {
	// If the following call pancis, it indicates UnimplementedConfigMapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigMap_ServiceDesc, srv)
}

func _ConfigMap_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMapListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigMapServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigMap_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigMapServer).List(ctx, req.(*ConfigMapListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigMap_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMapGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigMapServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigMap_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigMapServer).Get(ctx, req.(*ConfigMapGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigMap_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMapCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigMapServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigMap_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigMapServer).Create(ctx, req.(*ConfigMapCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigMap_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMapUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigMapServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigMap_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigMapServer).Update(ctx, req.(*ConfigMapUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigMap_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMapGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigMapServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigMap_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigMapServer).Delete(ctx, req.(*ConfigMapGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigMap_ServiceDesc is the grpc.ServiceDesc for ConfigMap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigMap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kusec_v1.ConfigMap",
	HandlerType: (*ConfigMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ConfigMap_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ConfigMap_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ConfigMap_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ConfigMap_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConfigMap_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kusec_v1/configmap.proto",
}
