// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/configmap.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigMapMain struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AppId       string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Active      bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	SlugName    string                 `protobuf:"bytes,6,opt,name=slug_name,json=slugName,proto3" json:"slug_name,omitempty"`
	Description string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	// Полное имя итогового k8s-configmap; вычисляется бэкендом.
	KubeConfigmapName string `protobuf:"bytes,8,opt,name=kube_configmap_name,json=kubeConfigmapName,proto3" json:"kube_configmap_name,omitempty"`
	// При true имя k8s-configmap = slug_name без префикса и app-slug.
	// Менять флаг могут только админы.
	ExactSlug     bool `protobuf:"varint,9,opt,name=exact_slug,json=exactSlug,proto3" json:"exact_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapMain) Reset() {
	*x = ConfigMapMain{}
	mi := &file_kusec_v1_configmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapMain) ProtoMessage() {}

func (x *ConfigMapMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapMain.ProtoReflect.Descriptor instead.
func (*ConfigMapMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configmap_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMapMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigMapMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigMapMain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfigMapMain) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ConfigMapMain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ConfigMapMain) GetSlugName() string {
	if x != nil {
		return x.SlugName
	}
	return ""
}

func (x *ConfigMapMain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigMapMain) GetKubeConfigmapName() string {
	if x != nil {
		return x.KubeConfigmapName
	}
	return ""
}

func (x *ConfigMapMain) GetExactSlug() bool {
	if x != nil {
		return x.ExactSlug
	}
	return false
}

type ConfigMapListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *ListParamsSt          `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	AppId         *string                `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	Active        *bool                  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapListReq) Reset() {
	*x = ConfigMapListReq{}
	mi := &file_kusec_v1_configmap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapListReq) ProtoMessage() {}

func (x *ConfigMapListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configmap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapListReq.ProtoReflect.Descriptor instead.
func (*ConfigMapListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configmap_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigMapListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *ConfigMapListReq) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *ConfigMapListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ConfigMapListReq) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type ConfigMapListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*ConfigMapMain       `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigMapListRep) Reset() {
	*x = ConfigMapListRep{}
	mi := &file_kusec_v1_configmap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapListRep) ProtoMessage() {}

func (x *ConfigMapListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configmap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapListRep.ProtoReflect.Descriptor instead.
func (*ConfigMapListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configmap_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigMapListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *ConfigMapListRep) GetResults() []*ConfigMapMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type ConfigMapGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapGetReq) Reset() {
	*x = ConfigMapGetReq{}
	mi := &file_kusec_v1_configmap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapGetReq) ProtoMessage() {}

func (x *ConfigMapGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configmap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapGetReq.ProtoReflect.Descriptor instead.
func (*ConfigMapGetReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configmap_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigMapGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfigMapCreateReq struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AppId       string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Active      *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	SlugName    string                 `protobuf:"bytes,3,opt,name=slug_name,json=slugName,proto3" json:"slug_name,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Имя без префикса и app-slug. Установка true доступна только админам.
	ExactSlug     bool `protobuf:"varint,5,opt,name=exact_slug,json=exactSlug,proto3" json:"exact_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapCreateReq) Reset() {
	*x = ConfigMapCreateReq{}
	mi := &file_kusec_v1_configmap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapCreateReq) ProtoMessage() {}

func (x *ConfigMapCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configmap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapCreateReq.ProtoReflect.Descriptor instead.
func (*ConfigMapCreateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configmap_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigMapCreateReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ConfigMapCreateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ConfigMapCreateReq) GetSlugName() string {
	if x != nil {
		return x.SlugName
	}
	return ""
}

func (x *ConfigMapCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigMapCreateReq) GetExactSlug() bool {
	if x != nil {
		return x.ExactSlug
	}
	return false
}

type ConfigMapCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapCreateRep) Reset() {
	*x = ConfigMapCreateRep{}
	mi := &file_kusec_v1_configmap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapCreateRep) ProtoMessage() {}

func (x *ConfigMapCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configmap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapCreateRep.ProtoReflect.Descriptor instead.
func (*ConfigMapCreateRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configmap_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigMapCreateRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfigMapUpdateReq struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId       *string                `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	Active      *bool                  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	SlugName    *string                `protobuf:"bytes,4,opt,name=slug_name,json=slugName,proto3,oneof" json:"slug_name,omitempty"`
	Description *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Изменение флага доступно только админам.
	ExactSlug     *bool `protobuf:"varint,6,opt,name=exact_slug,json=exactSlug,proto3,oneof" json:"exact_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapUpdateReq) Reset() {
	*x = ConfigMapUpdateReq{}
	mi := &file_kusec_v1_configmap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapUpdateReq) ProtoMessage() {}

func (x *ConfigMapUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_configmap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapUpdateReq.ProtoReflect.Descriptor instead.
func (*ConfigMapUpdateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_configmap_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigMapUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigMapUpdateReq) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *ConfigMapUpdateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ConfigMapUpdateReq) GetSlugName() string {
	if x != nil && x.SlugName != nil {
		return *x.SlugName
	}
	return ""
}

func (x *ConfigMapUpdateReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ConfigMapUpdateReq) GetExactSlug() bool {
	if x != nil && x.ExactSlug != nil {
		return *x.ExactSlug
	}
	return false
}

var File_kusec_v1_configmap_proto protoreflect.FileDescriptor

const file_kusec_v1_configmap_proto_rawDesc = "" +
	"\n" +
	"\x18kusec_v1/configmap.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15kusec_v1/common.proto\"\xd2\x02\n" +
	"\rConfigMapMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\tR\x05appId\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x1b\n" +
	"\tslug_name\x18\x06 \x01(\tR\bslugName\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12.\n" +
	"\x13kube_configmap_name\x18\b \x01(\tR\x11kubeConfigmapName\x12\x1d\n" +
	"\n" +
	"exact_slug\x18\t \x01(\bR\texactSlug\"\xc2\x01\n" +
	"\x10ConfigMapListReq\x127\n" +
	"\vlist_params\x18\x01 \x01(\v2\x16.kusec_v1.ListParamsStR\n" +
	"listParams\x12\x1a\n" +
	"\x06app_id\x18\x02 \x01(\tH\x00R\x05appId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x02R\x06search\x88\x01\x01B\t\n" +
	"\a_app_idB\t\n" +
	"\a_activeB\t\n" +
	"\a_search\"\x8a\x01\n" +
	"\x10ConfigMapListRep\x12C\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x1a.kusec_v1.PaginationInfoStR\x0epaginationInfo\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.kusec_v1.ConfigMapMainR\aresults\"!\n" +
	"\x0fConfigMapGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb1\x01\n" +
	"\x12ConfigMapCreateReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x1b\n" +
	"\tslug_name\x18\x03 \x01(\tR\bslugName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"exact_slug\x18\x05 \x01(\bR\texactSlugB\t\n" +
	"\a_active\"$\n" +
	"\x12ConfigMapCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8d\x02\n" +
	"\x12ConfigMapUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\x06app_id\x18\x02 \x01(\tH\x00R\x05appId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01\x12 \n" +
	"\tslug_name\x18\x04 \x01(\tH\x02R\bslugName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"exact_slug\x18\x06 \x01(\bH\x04R\texactSlug\x88\x01\x01B\t\n" +
	"\a_app_idB\t\n" +
	"\a_activeB\f\n" +
	"\n" +
	"_slug_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_exact_slug2\xc2\x03\n" +
	"\tConfigMap\x12R\n" +
	"\x04List\x12\x1a.kusec_v1.ConfigMapListReq\x1a\x1a.kusec_v1.ConfigMapListRep\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/configmap\x12R\n" +
	"\x03Get\x12\x19.kusec_v1.ConfigMapGetReq\x1a\x17.kusec_v1.ConfigMapMain\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/configmap/{id}\x12[\n" +
	"\x06Create\x12\x1c.kusec_v1.ConfigMapCreateReq\x1a\x1c.kusec_v1.ConfigMapCreateRep\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/configmap\x12Z\n" +
	"\x06Update\x12\x1c.kusec_v1.ConfigMapUpdateReq\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/configmap/{id}\x12T\n" +
	"\x06Delete\x12\x19.kusec_v1.ConfigMapGetReq\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/configmap/{id}B\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_configmap_proto_rawDescOnce sync.Once
	file_kusec_v1_configmap_proto_rawDescData []byte
)

func file_kusec_v1_configmap_proto_rawDescGZIP() []byte {
	file_kusec_v1_configmap_proto_rawDescOnce.Do(func() {
		file_kusec_v1_configmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_configmap_proto_rawDesc), len(file_kusec_v1_configmap_proto_rawDesc)))
	})
	return file_kusec_v1_configmap_proto_rawDescData
}

var file_kusec_v1_configmap_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kusec_v1_configmap_proto_goTypes = []any{
	(*ConfigMapMain)(nil),         // 0: kusec_v1.ConfigMapMain
	(*ConfigMapListReq)(nil),      // 1: kusec_v1.ConfigMapListReq
	(*ConfigMapListRep)(nil),      // 2: kusec_v1.ConfigMapListRep
	(*ConfigMapGetReq)(nil),       // 3: kusec_v1.ConfigMapGetReq
	(*ConfigMapCreateReq)(nil),    // 4: kusec_v1.ConfigMapCreateReq
	(*ConfigMapCreateRep)(nil),    // 5: kusec_v1.ConfigMapCreateRep
	(*ConfigMapUpdateReq)(nil),    // 6: kusec_v1.ConfigMapUpdateReq
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*ListParamsSt)(nil),          // 8: kusec_v1.ListParamsSt
	(*PaginationInfoSt)(nil),      // 9: kusec_v1.PaginationInfoSt
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_kusec_v1_configmap_proto_depIdxs = []int32{
	7,  // 0: kusec_v1.ConfigMapMain.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: kusec_v1.ConfigMapMain.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: kusec_v1.ConfigMapListReq.list_params:type_name -> kusec_v1.ListParamsSt
	9,  // 3: kusec_v1.ConfigMapListRep.pagination_info:type_name -> kusec_v1.PaginationInfoSt
	0,  // 4: kusec_v1.ConfigMapListRep.results:type_name -> kusec_v1.ConfigMapMain
	1,  // 5: kusec_v1.ConfigMap.List:input_type -> kusec_v1.ConfigMapListReq
	3,  // 6: kusec_v1.ConfigMap.Get:input_type -> kusec_v1.ConfigMapGetReq
	4,  // 7: kusec_v1.ConfigMap.Create:input_type -> kusec_v1.ConfigMapCreateReq
	6,  // 8: kusec_v1.ConfigMap.Update:input_type -> kusec_v1.ConfigMapUpdateReq
	3,  // 9: kusec_v1.ConfigMap.Delete:input_type -> kusec_v1.ConfigMapGetReq
	2,  // 10: kusec_v1.ConfigMap.List:output_type -> kusec_v1.ConfigMapListRep
	0,  // 11: kusec_v1.ConfigMap.Get:output_type -> kusec_v1.ConfigMapMain
	5,  // 12: kusec_v1.ConfigMap.Create:output_type -> kusec_v1.ConfigMapCreateRep
	10, // 13: kusec_v1.ConfigMap.Update:output_type -> google.protobuf.Empty
	10, // 14: kusec_v1.ConfigMap.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_kusec_v1_configmap_proto_init() }
func file_kusec_v1_configmap_proto_init() {
	if File_kusec_v1_configmap_proto != nil {
		return
	}
	file_kusec_v1_common_proto_init()
	file_kusec_v1_configmap_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_configmap_proto_msgTypes[4].OneofWrappers = []any{}
	file_kusec_v1_configmap_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_configmap_proto_rawDesc), len(file_kusec_v1_configmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_configmap_proto_goTypes,
		DependencyIndexes: file_kusec_v1_configmap_proto_depIdxs,
		MessageInfos:      file_kusec_v1_configmap_proto_msgTypes,
	}.Build()
	File_kusec_v1_configmap_proto = out.File
	file_kusec_v1_configmap_proto_goTypes = nil
	file_kusec_v1_configmap_proto_depIdxs = nil
}
