// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: kusec_v1/configitem.proto

package kusec_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigItem_List_FullMethodName   = "/kusec_v1.ConfigItem/List"
	ConfigItem_Get_FullMethodName    = "/kusec_v1.ConfigItem/Get"
	ConfigItem_Create_FullMethodName = "/kusec_v1.ConfigItem/Create"
	ConfigItem_Update_FullMethodName = "/kusec_v1.ConfigItem/Update"
	ConfigItem_Delete_FullMethodName = "/kusec_v1.ConfigItem/Delete"
)

// ConfigItemClient is the client API for ConfigItem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigItemClient interface {
	List(ctx context.Context, in *ConfigItemListReq, opts ...grpc.CallOption) (*ConfigItemListRep, error)
	Get(ctx context.Context, in *ConfigItemGetReq, opts ...grpc.CallOption) (*ConfigItemMain, error)
	Create(ctx context.Context, in *ConfigItemCreateReq, opts ...grpc.CallOption) (*ConfigItemCreateRep, error)
	Update(ctx context.Context, in *ConfigItemUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *ConfigItemGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type configItemClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigItemClient(cc grpc.ClientConnInterface) ConfigItemClient {
	return &configItemClient{cc}
}

func (c *configItemClient) List(ctx context.Context, in *ConfigItemListReq, opts ...grpc.CallOption) (*ConfigItemListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigItemListRep)
	err := c.cc.Invoke(ctx, ConfigItem_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemClient) Get(ctx context.Context, in *ConfigItemGetReq, opts ...grpc.CallOption) (*ConfigItemMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigItemMain)
	err := c.cc.Invoke(ctx, ConfigItem_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemClient) Create(ctx context.Context, in *ConfigItemCreateReq, opts ...grpc.CallOption) (*ConfigItemCreateRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigItemCreateRep)
	err := c.cc.Invoke(ctx, ConfigItem_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemClient) Update(ctx context.Context, in *ConfigItemUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConfigItem_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemClient) Delete(ctx context.Context, in *ConfigItemGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConfigItem_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigItemServer is the server API for ConfigItem service.
// All implementations must embed UnimplementedConfigItemServer
// for forward compatibility.
type ConfigItemServer interface {
	List(context.Context, *ConfigItemListReq) (*ConfigItemListRep, error)
	Get(context.Context, *ConfigItemGetReq) (*ConfigItemMain, error)
	Create(context.Context, *ConfigItemCreateReq) (*ConfigItemCreateRep, error)
	Update(context.Context, *ConfigItemUpdateReq) (*emptypb.Empty, error)
	Delete(context.Context, *ConfigItemGetReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedConfigItemServer()
}

// UnimplementedConfigItemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigItemServer struct{}

func (UnimplementedConfigItemServer) List(context.Context, *ConfigItemListReq) (*ConfigItemListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConfigItemServer) Get(context.Context, *ConfigItemGetReq) (*ConfigItemMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConfigItemServer) Create(context.Context, *ConfigItemCreateReq) (*ConfigItemCreateRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedConfigItemServer) Update(context.Context, *ConfigItemUpdateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedConfigItemServer) Delete(context.Context, *ConfigItemGetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConfigItemServer) mustEmbedUnimplementedConfigItemServer() {}
func (UnimplementedConfigItemServer) testEmbeddedByValue()                    {}

// UnsafeConfigItemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigItemServer will
// result in compilation errors.
type UnsafeConfigItemServer interface {
	mustEmbedUnimplementedConfigItemServer()
}

func RegisterConfigItemServer(s grpc.ServiceRegistrar, srv ConfigItemServer) {
	// If the following call pancis, it indicates UnimplementedConfigItemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigItem_ServiceDesc, srv)
}

func _ConfigItem_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigItemListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItem_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServer).List(ctx, req.(*ConfigItemListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItem_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigItemGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItem_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServer).Get(ctx, req.(*ConfigItemGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItem_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigItemCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItem_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServer).Create(ctx, req.(*ConfigItemCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItem_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigItemUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItem_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServer).Update(ctx, req.(*ConfigItemUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItem_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigItemGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItem_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServer).Delete(ctx, req.(*ConfigItemGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigItem_ServiceDesc is the grpc.ServiceDesc for ConfigItem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigItem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kusec_v1.ConfigItem",
	HandlerType: (*ConfigItemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ConfigItem_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ConfigItem_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ConfigItem_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ConfigItem_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConfigItem_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kusec_v1/configitem.proto",
}
