// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/dashboard.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardCountSt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Active        int64                  `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardCountSt) Reset() {
	*x = DashboardCountSt{}
	mi := &file_kusec_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardCountSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardCountSt) ProtoMessage() {}

func (x *DashboardCountSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardCountSt.ProtoReflect.Descriptor instead.
func (*DashboardCountSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardCountSt) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DashboardCountSt) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

type DashboardRecentSecretSt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Имя приложения, к которому относится секрет (для отображения).
	AppName     string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	SlugName    string                 `protobuf:"bytes,4,opt,name=slug_name,json=slugName,proto3" json:"slug_name,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Active      bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Количество items в секрете.
	ItemCount     int64 `protobuf:"varint,8,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardRecentSecretSt) Reset() {
	*x = DashboardRecentSecretSt{}
	mi := &file_kusec_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRecentSecretSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRecentSecretSt) ProtoMessage() {}

func (x *DashboardRecentSecretSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRecentSecretSt.ProtoReflect.Descriptor instead.
func (*DashboardRecentSecretSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardRecentSecretSt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DashboardRecentSecretSt) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DashboardRecentSecretSt) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DashboardRecentSecretSt) GetSlugName() string {
	if x != nil {
		return x.SlugName
	}
	return ""
}

func (x *DashboardRecentSecretSt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DashboardRecentSecretSt) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DashboardRecentSecretSt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DashboardRecentSecretSt) GetItemCount() int64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type DashboardRep struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	App           *DashboardCountSt          `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Secret        *DashboardCountSt          `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Item          *DashboardCountSt          `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Usr           *DashboardCountSt          `protobuf:"bytes,4,opt,name=usr,proto3" json:"usr,omitempty"`
	RecentSecrets []*DashboardRecentSecretSt `protobuf:"bytes,5,rep,name=recent_secrets,json=recentSecrets,proto3" json:"recent_secrets,omitempty"`
	Configmap     *DashboardCountSt          `protobuf:"bytes,6,opt,name=configmap,proto3" json:"configmap,omitempty"`
	ConfigItem    *DashboardCountSt          `protobuf:"bytes,7,opt,name=config_item,json=configItem,proto3" json:"config_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardRep) Reset() {
	*x = DashboardRep{}
	mi := &file_kusec_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRep) ProtoMessage() {}

func (x *DashboardRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRep.ProtoReflect.Descriptor instead.
func (*DashboardRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardRep) GetApp() *DashboardCountSt {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *DashboardRep) GetSecret() *DashboardCountSt {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *DashboardRep) GetItem() *DashboardCountSt {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *DashboardRep) GetUsr() *DashboardCountSt {
	if x != nil {
		return x.Usr
	}
	return nil
}

func (x *DashboardRep) GetRecentSecrets() []*DashboardRecentSecretSt {
	if x != nil {
		return x.RecentSecrets
	}
	return nil
}

func (x *DashboardRep) GetConfigmap() *DashboardCountSt {
	if x != nil {
		return x.Configmap
	}
	return nil
}

func (x *DashboardRep) GetConfigItem() *DashboardCountSt {
	if x != nil {
		return x.ConfigItem
	}
	return nil
}

var File_kusec_v1_dashboard_proto protoreflect.FileDescriptor

const file_kusec_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x18kusec_v1/dashboard.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\x10DashboardCountSt\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x16\n" +
	"\x06active\x18\x02 \x01(\x03R\x06active\"\x8c\x02\n" +
	"\x17DashboardRecentSecretSt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x1b\n" +
	"\tslug_name\x18\x04 \x01(\tR\bslugName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"item_count\x18\b \x01(\x03R\titemCount\"\x8f\x03\n" +
	"\fDashboardRep\x12,\n" +
	"\x03app\x18\x01 \x01(\v2\x1a.kusec_v1.DashboardCountStR\x03app\x122\n" +
	"\x06secret\x18\x02 \x01(\v2\x1a.kusec_v1.DashboardCountStR\x06secret\x12.\n" +
	"\x04item\x18\x03 \x01(\v2\x1a.kusec_v1.DashboardCountStR\x04item\x12,\n" +
	"\x03usr\x18\x04 \x01(\v2\x1a.kusec_v1.DashboardCountStR\x03usr\x12H\n" +
	"\x0erecent_secrets\x18\x05 \x03(\v2!.kusec_v1.DashboardRecentSecretStR\rrecentSecrets\x128\n" +
	"\tconfigmap\x18\x06 \x01(\v2\x1a.kusec_v1.DashboardCountStR\tconfigmap\x12;\n" +
	"\vconfig_item\x18\a \x01(\v2\x1a.kusec_v1.DashboardCountStR\n" +
	"configItem2V\n" +
	"\tDashboard\x12I\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x16.kusec_v1.DashboardRep\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/dashboardB\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_dashboard_proto_rawDescOnce sync.Once
	file_kusec_v1_dashboard_proto_rawDescData []byte
)

func file_kusec_v1_dashboard_proto_rawDescGZIP() []byte {
	file_kusec_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_kusec_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_dashboard_proto_rawDesc), len(file_kusec_v1_dashboard_proto_rawDesc)))
	})
	return file_kusec_v1_dashboard_proto_rawDescData
}

var file_kusec_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kusec_v1_dashboard_proto_goTypes = []any{
	(*DashboardCountSt)(nil),        // 0: kusec_v1.DashboardCountSt
	(*DashboardRecentSecretSt)(nil), // 1: kusec_v1.DashboardRecentSecretSt
	(*DashboardRep)(nil),            // 2: kusec_v1.DashboardRep
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 4: google.protobuf.Empty
}
var file_kusec_v1_dashboard_proto_depIdxs = []int32{
	3, // 0: kusec_v1.DashboardRecentSecretSt.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: kusec_v1.DashboardRep.app:type_name -> kusec_v1.DashboardCountSt
	0, // 2: kusec_v1.DashboardRep.secret:type_name -> kusec_v1.DashboardCountSt
	0, // 3: kusec_v1.DashboardRep.item:type_name -> kusec_v1.DashboardCountSt
	0, // 4: kusec_v1.DashboardRep.usr:type_name -> kusec_v1.DashboardCountSt
	1, // 5: kusec_v1.DashboardRep.recent_secrets:type_name -> kusec_v1.DashboardRecentSecretSt
	0, // 6: kusec_v1.DashboardRep.configmap:type_name -> kusec_v1.DashboardCountSt
	0, // 7: kusec_v1.DashboardRep.config_item:type_name -> kusec_v1.DashboardCountSt
	4, // 8: kusec_v1.Dashboard.Get:input_type -> google.protobuf.Empty
	2, // 9: kusec_v1.Dashboard.Get:output_type -> kusec_v1.DashboardRep
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_kusec_v1_dashboard_proto_init() }
func file_kusec_v1_dashboard_proto_init() {
	if File_kusec_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_dashboard_proto_rawDesc), len(file_kusec_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_kusec_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_kusec_v1_dashboard_proto_msgTypes,
	}.Build()
	File_kusec_v1_dashboard_proto = out.File
	file_kusec_v1_dashboard_proto_goTypes = nil
	file_kusec_v1_dashboard_proto_depIdxs = nil
}
