// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/item.proto

package kusec_v1

import (
	common "github.com/mechta-market/kusec/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SecretId      string                 `protobuf:"bytes,4,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	ValueFormat   string                 `protobuf:"bytes,9,opt,name=value_format,json=valueFormat,proto3" json:"value_format,omitempty"`
	Encoding      string                 `protobuf:"bytes,10,opt,name=encoding,proto3" json:"encoding,omitempty"`
	FileName      string                 `protobuf:"bytes,11,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,12,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemMain) Reset() {
	*x = ItemMain{}
	mi := &file_kusec_v1_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMain) ProtoMessage() {}

func (x *ItemMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMain.ProtoReflect.Descriptor instead.
func (*ItemMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ItemMain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ItemMain) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *ItemMain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ItemMain) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ItemMain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ItemMain) GetValueFormat() string {
	if x != nil {
		return x.ValueFormat
	}
	return ""
}

func (x *ItemMain) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *ItemMain) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ItemMain) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ItemMain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ItemListReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ListParams *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	SecretId   *string                `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3,oneof" json:"secret_id,omitempty"`
	Active     *bool                  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Search     *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	// Выборка по нескольким секретам за один запрос (без пагинации).
	SecretIds     []string `protobuf:"bytes,5,rep,name=secret_ids,json=secretIds,proto3" json:"secret_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListReq) Reset() {
	*x = ItemListReq{}
	mi := &file_kusec_v1_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListReq) ProtoMessage() {}

func (x *ItemListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListReq.ProtoReflect.Descriptor instead.
func (*ItemListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *ItemListReq) GetSecretId() string {
	if x != nil && x.SecretId != nil {
		return *x.SecretId
	}
	return ""
}

func (x *ItemListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ItemListReq) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ItemListReq) GetSecretIds() []string {
	if x != nil {
		return x.SecretIds
	}
	return nil
}

type ItemListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*ItemMain              `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ItemListRep) Reset() {
	*x = ItemListRep{}
	mi := &file_kusec_v1_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListRep) ProtoMessage() {}

func (x *ItemListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListRep.ProtoReflect.Descriptor instead.
func (*ItemListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *ItemListRep) GetResults() []*ItemMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type ItemGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemGetReq) Reset() {
	*x = ItemGetReq{}
	mi := &file_kusec_v1_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemGetReq) ProtoMessage() {}

func (x *ItemGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemGetReq.ProtoReflect.Descriptor instead.
func (*ItemGetReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_item_proto_rawDescGZIP(), []int{3}
}

func (x *ItemGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ItemCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueFormat   *string                `protobuf:"bytes,6,opt,name=value_format,json=valueFormat,proto3,oneof" json:"value_format,omitempty"`
	Encoding      *string                `protobuf:"bytes,7,opt,name=encoding,proto3,oneof" json:"encoding,omitempty"`
	FileName      *string                `protobuf:"bytes,8,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	ContentType   *string                `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCreateReq) Reset() {
	*x = ItemCreateReq{}
	mi := &file_kusec_v1_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCreateReq) ProtoMessage() {}

func (x *ItemCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCreateReq.ProtoReflect.Descriptor instead.
func (*ItemCreateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_item_proto_rawDescGZIP(), []int{4}
}

func (x *ItemCreateReq) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *ItemCreateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ItemCreateReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ItemCreateReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ItemCreateReq) GetValueFormat() string {
	if x != nil && x.ValueFormat != nil {
		return *x.ValueFormat
	}
	return ""
}

func (x *ItemCreateReq) GetEncoding() string {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return ""
}

func (x *ItemCreateReq) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *ItemCreateReq) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *ItemCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ItemCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCreateRep) Reset() {
	*x = ItemCreateRep{}
	mi := &file_kusec_v1_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCreateRep) ProtoMessage() {}

func (x *ItemCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCreateRep.ProtoReflect.Descriptor instead.
func (*ItemCreateRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_item_proto_rawDescGZIP(), []int{5}
}

func (x *ItemCreateRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ItemUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretId      *string                `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3,oneof" json:"secret_id,omitempty"`
	Active        *bool                  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Key           *string                `protobuf:"bytes,4,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,5,opt,name=value,proto3,oneof" json:"value,omitempty"`
	ValueFormat   *string                `protobuf:"bytes,7,opt,name=value_format,json=valueFormat,proto3,oneof" json:"value_format,omitempty"`
	Encoding      *string                `protobuf:"bytes,8,opt,name=encoding,proto3,oneof" json:"encoding,omitempty"`
	FileName      *string                `protobuf:"bytes,9,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	ContentType   *string                `protobuf:"bytes,10,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUpdateReq) Reset() {
	*x = ItemUpdateReq{}
	mi := &file_kusec_v1_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUpdateReq) ProtoMessage() {}

func (x *ItemUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUpdateReq.ProtoReflect.Descriptor instead.
func (*ItemUpdateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_item_proto_rawDescGZIP(), []int{6}
}

func (x *ItemUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemUpdateReq) GetSecretId() string {
	if x != nil && x.SecretId != nil {
		return *x.SecretId
	}
	return ""
}

func (x *ItemUpdateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ItemUpdateReq) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ItemUpdateReq) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *ItemUpdateReq) GetValueFormat() string {
	if x != nil && x.ValueFormat != nil {
		return *x.ValueFormat
	}
	return ""
}

func (x *ItemUpdateReq) GetEncoding() string {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return ""
}

func (x *ItemUpdateReq) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *ItemUpdateReq) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *ItemUpdateReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_kusec_v1_item_proto protoreflect.FileDescriptor

const file_kusec_v1_item_proto_rawDesc = "" +
	"\n" +
	"\x13kusec_v1/item.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x8e\x03\n" +
	"\bItemMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tsecret_id\x18\x04 \x01(\tR\bsecretId\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12!\n" +
	"\fvalue_format\x18\t \x01(\tR\vvalueFormat\x12\x1a\n" +
	"\bencoding\x18\n" +
	" \x01(\tR\bencoding\x12\x1b\n" +
	"\tfile_name\x18\v \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\f \x01(\tR\vcontentType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xe3\x01\n" +
	"\vItemListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12 \n" +
	"\tsecret_id\x18\x02 \x01(\tH\x00R\bsecretId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x02R\x06search\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"secret_ids\x18\x05 \x03(\tR\tsecretIdsB\f\n" +
	"\n" +
	"_secret_idB\t\n" +
	"\a_activeB\t\n" +
	"\a_search\"~\n" +
	"\vItemListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x12,\n" +
	"\aresults\x18\x02 \x03(\v2\x12.kusec_v1.ItemMainR\aresults\"\x1c\n" +
	"\n" +
	"ItemGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xee\x02\n" +
	"\rItemCreateReq\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12&\n" +
	"\fvalue_format\x18\x06 \x01(\tH\x01R\vvalueFormat\x88\x01\x01\x12\x1f\n" +
	"\bencoding\x18\a \x01(\tH\x02R\bencoding\x88\x01\x01\x12 \n" +
	"\tfile_name\x18\b \x01(\tH\x03R\bfileName\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\t \x01(\tH\x04R\vcontentType\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescriptionB\t\n" +
	"\a_activeB\x0f\n" +
	"\r_value_formatB\v\n" +
	"\t_encodingB\f\n" +
	"\n" +
	"_file_nameB\x0f\n" +
	"\r_content_type\"\x1f\n" +
	"\rItemCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc2\x03\n" +
	"\rItemUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tsecret_id\x18\x02 \x01(\tH\x00R\bsecretId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x04 \x01(\tH\x02R\x03key\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x05 \x01(\tH\x03R\x05value\x88\x01\x01\x12&\n" +
	"\fvalue_format\x18\a \x01(\tH\x04R\vvalueFormat\x88\x01\x01\x12\x1f\n" +
	"\bencoding\x18\b \x01(\tH\x05R\bencoding\x88\x01\x01\x12 \n" +
	"\tfile_name\x18\t \x01(\tH\x06R\bfileName\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\n" +
	" \x01(\tH\aR\vcontentType\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\bR\vdescription\x88\x01\x01B\f\n" +
	"\n" +
	"_secret_idB\t\n" +
	"\a_activeB\x06\n" +
	"\x04_keyB\b\n" +
	"\x06_valueB\x0f\n" +
	"\r_value_formatB\v\n" +
	"\t_encodingB\f\n" +
	"\n" +
	"_file_nameB\x0f\n" +
	"\r_content_typeB\x0e\n" +
	"\f_description2\xfc\x02\n" +
	"\x04Item\x12C\n" +
	"\x04List\x12\x15.kusec_v1.ItemListReq\x1a\x15.kusec_v1.ItemListRep\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/item\x12C\n" +
	"\x03Get\x12\x14.kusec_v1.ItemGetReq\x1a\x12.kusec_v1.ItemMain\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/item/{id}\x12L\n" +
	"\x06Create\x12\x17.kusec_v1.ItemCreateReq\x1a\x17.kusec_v1.ItemCreateRep\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/item\x12P\n" +
	"\x06Update\x12\x17.kusec_v1.ItemUpdateReq\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\x1a\n" +
	"/item/{id}\x12J\n" +
	"\x06Delete\x12\x14.kusec_v1.ItemGetReq\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/item/{id}B\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_item_proto_rawDescOnce sync.Once
	file_kusec_v1_item_proto_rawDescData []byte
)

func file_kusec_v1_item_proto_rawDescGZIP() []byte {
	file_kusec_v1_item_proto_rawDescOnce.Do(func() {
		file_kusec_v1_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_item_proto_rawDesc), len(file_kusec_v1_item_proto_rawDesc)))
	})
	return file_kusec_v1_item_proto_rawDescData
}

var file_kusec_v1_item_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kusec_v1_item_proto_goTypes = []any{
	(*ItemMain)(nil),                // 0: kusec_v1.ItemMain
	(*ItemListReq)(nil),             // 1: kusec_v1.ItemListReq
	(*ItemListRep)(nil),             // 2: kusec_v1.ItemListRep
	(*ItemGetReq)(nil),              // 3: kusec_v1.ItemGetReq
	(*ItemCreateReq)(nil),           // 4: kusec_v1.ItemCreateReq
	(*ItemCreateRep)(nil),           // 5: kusec_v1.ItemCreateRep
	(*ItemUpdateReq)(nil),           // 6: kusec_v1.ItemUpdateReq
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 8: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 9: common.PaginationInfoSt
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_kusec_v1_item_proto_depIdxs = []int32{
	7,  // 0: kusec_v1.ItemMain.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: kusec_v1.ItemMain.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: kusec_v1.ItemListReq.list_params:type_name -> common.ListParamsSt
	9,  // 3: kusec_v1.ItemListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 4: kusec_v1.ItemListRep.results:type_name -> kusec_v1.ItemMain
	1,  // 5: kusec_v1.Item.List:input_type -> kusec_v1.ItemListReq
	3,  // 6: kusec_v1.Item.Get:input_type -> kusec_v1.ItemGetReq
	4,  // 7: kusec_v1.Item.Create:input_type -> kusec_v1.ItemCreateReq
	6,  // 8: kusec_v1.Item.Update:input_type -> kusec_v1.ItemUpdateReq
	3,  // 9: kusec_v1.Item.Delete:input_type -> kusec_v1.ItemGetReq
	2,  // 10: kusec_v1.Item.List:output_type -> kusec_v1.ItemListRep
	0,  // 11: kusec_v1.Item.Get:output_type -> kusec_v1.ItemMain
	5,  // 12: kusec_v1.Item.Create:output_type -> kusec_v1.ItemCreateRep
	10, // 13: kusec_v1.Item.Update:output_type -> google.protobuf.Empty
	10, // 14: kusec_v1.Item.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_kusec_v1_item_proto_init() }
func file_kusec_v1_item_proto_init() {
	if File_kusec_v1_item_proto != nil {
		return
	}
	file_kusec_v1_item_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_item_proto_msgTypes[4].OneofWrappers = []any{}
	file_kusec_v1_item_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_item_proto_rawDesc), len(file_kusec_v1_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_item_proto_goTypes,
		DependencyIndexes: file_kusec_v1_item_proto_depIdxs,
		MessageInfos:      file_kusec_v1_item_proto_msgTypes,
	}.Build()
	File_kusec_v1_item_proto = out.File
	file_kusec_v1_item_proto_goTypes = nil
	file_kusec_v1_item_proto_depIdxs = nil
}
