// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/kube.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KubeListNamespacesRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false — сервис запущен вне кластера (namespaces тогда пуст).
	InCluster bool `protobuf:"varint,1,opt,name=in_cluster,json=inCluster,proto3" json:"in_cluster,omitempty"`
	// Имена namespace-ов кластера без системных kube-*.
	Namespaces    []string `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeListNamespacesRep) Reset() {
	*x = KubeListNamespacesRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeListNamespacesRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeListNamespacesRep) ProtoMessage() {}

func (x *KubeListNamespacesRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeListNamespacesRep.ProtoReflect.Descriptor instead.
func (*KubeListNamespacesRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{0}
}

func (x *KubeListNamespacesRep) GetInCluster() bool {
	if x != nil {
		return x.InCluster
	}
	return false
}

func (x *KubeListNamespacesRep) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type KubeSyncSecretsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncSecretsReq) Reset() {
	*x = KubeSyncSecretsReq{}
	mi := &file_kusec_v1_kube_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncSecretsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncSecretsReq) ProtoMessage() {}

func (x *KubeSyncSecretsReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncSecretsReq.ProtoReflect.Descriptor instead.
func (*KubeSyncSecretsReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{1}
}

func (x *KubeSyncSecretsReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type KubeSyncSecretsRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Списки в формате "namespace/name".
	Created   []string `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	Updated   []string `protobuf:"bytes,2,rep,name=updated,proto3" json:"updated,omitempty"`
	Deleted   []string `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"`
	Unchanged int64    `protobuf:"varint,4,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	// Ошибки по отдельным секретам (sync продолжается для остальных).
	Errors        []string `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncSecretsRep) Reset() {
	*x = KubeSyncSecretsRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncSecretsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncSecretsRep) ProtoMessage() {}

func (x *KubeSyncSecretsRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncSecretsRep.ProtoReflect.Descriptor instead.
func (*KubeSyncSecretsRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{2}
}

func (x *KubeSyncSecretsRep) GetCreated() []string {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *KubeSyncSecretsRep) GetUpdated() []string {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *KubeSyncSecretsRep) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *KubeSyncSecretsRep) GetUnchanged() int64 {
	if x != nil {
		return x.Unchanged
	}
	return 0
}

func (x *KubeSyncSecretsRep) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_kusec_v1_kube_proto protoreflect.FileDescriptor

const file_kusec_v1_kube_proto_rawDesc = "" +
	"\n" +
	"\x13kusec_v1/kube.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"V\n" +
	"\x15KubeListNamespacesRep\x12\x1d\n" +
	"\n" +
	"in_cluster\x18\x01 \x01(\bR\tinCluster\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\"+\n" +
	"\x12KubeSyncSecretsReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x98\x01\n" +
	"\x12KubeSyncSecretsRep\x12\x18\n" +
	"\acreated\x18\x01 \x03(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x03(\tR\aupdated\x12\x18\n" +
	"\adeleted\x18\x03 \x03(\tR\adeleted\x12\x1c\n" +
	"\tunchanged\x18\x04 \x01(\x03R\tunchanged\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors2\xd3\x01\n" +
	"\x04Kube\x12g\n" +
	"\vSyncSecrets\x12\x1c.kusec_v1.KubeSyncSecretsReq\x1a\x1c.kusec_v1.KubeSyncSecretsRep\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/kube/sync-secret\x12b\n" +
	"\x0eListNamespaces\x12\x16.google.protobuf.Empty\x1a\x1f.kusec_v1.KubeListNamespacesRep\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/kube/namespaceB\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_kube_proto_rawDescOnce sync.Once
	file_kusec_v1_kube_proto_rawDescData []byte
)

func file_kusec_v1_kube_proto_rawDescGZIP() []byte {
	file_kusec_v1_kube_proto_rawDescOnce.Do(func() {
		file_kusec_v1_kube_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_kube_proto_rawDesc), len(file_kusec_v1_kube_proto_rawDesc)))
	})
	return file_kusec_v1_kube_proto_rawDescData
}

var file_kusec_v1_kube_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kusec_v1_kube_proto_goTypes = []any{
	(*KubeListNamespacesRep)(nil), // 0: kusec_v1.KubeListNamespacesRep
	(*KubeSyncSecretsReq)(nil),    // 1: kusec_v1.KubeSyncSecretsReq
	(*KubeSyncSecretsRep)(nil),    // 2: kusec_v1.KubeSyncSecretsRep
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_kusec_v1_kube_proto_depIdxs = []int32{
	1, // 0: kusec_v1.Kube.SyncSecrets:input_type -> kusec_v1.KubeSyncSecretsReq
	3, // 1: kusec_v1.Kube.ListNamespaces:input_type -> google.protobuf.Empty
	2, // 2: kusec_v1.Kube.SyncSecrets:output_type -> kusec_v1.KubeSyncSecretsRep
	0, // 3: kusec_v1.Kube.ListNamespaces:output_type -> kusec_v1.KubeListNamespacesRep
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kusec_v1_kube_proto_init() }
func file_kusec_v1_kube_proto_init() {
	if File_kusec_v1_kube_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_kube_proto_rawDesc), len(file_kusec_v1_kube_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_kube_proto_goTypes,
		DependencyIndexes: file_kusec_v1_kube_proto_depIdxs,
		MessageInfos:      file_kusec_v1_kube_proto_msgTypes,
	}.Build()
	File_kusec_v1_kube_proto = out.File
	file_kusec_v1_kube_proto_goTypes = nil
	file_kusec_v1_kube_proto_depIdxs = nil
}
