// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/kube.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KubeListNamespacesRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false — сервис запущен вне кластера (namespaces тогда пуст).
	InCluster bool `protobuf:"varint,1,opt,name=in_cluster,json=inCluster,proto3" json:"in_cluster,omitempty"`
	// Имена namespace-ов кластера без системных kube-*.
	Namespaces    []string `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeListNamespacesRep) Reset() {
	*x = KubeListNamespacesRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeListNamespacesRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeListNamespacesRep) ProtoMessage() {}

func (x *KubeListNamespacesRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeListNamespacesRep.ProtoReflect.Descriptor instead.
func (*KubeListNamespacesRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{0}
}

func (x *KubeListNamespacesRep) GetInCluster() bool {
	if x != nil {
		return x.InCluster
	}
	return false
}

func (x *KubeListNamespacesRep) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type KubeListClusterSecretsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace для выборки; пусто — все namespace-ы без системных kube-*.
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeListClusterSecretsReq) Reset() {
	*x = KubeListClusterSecretsReq{}
	mi := &file_kusec_v1_kube_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeListClusterSecretsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeListClusterSecretsReq) ProtoMessage() {}

func (x *KubeListClusterSecretsReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeListClusterSecretsReq.ProtoReflect.Descriptor instead.
func (*KubeListClusterSecretsReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{1}
}

func (x *KubeListClusterSecretsReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type KubeClusterSecretSt struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Тип k8s-секрета (пусто = Opaque).
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Ключи data (отсортированы), значения не передаются.
	Keys []string `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	// true — секрет уже под управлением kusec (лейбл managed-by=kusec).
	Managed       bool `protobuf:"varint,5,opt,name=managed,proto3" json:"managed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeClusterSecretSt) Reset() {
	*x = KubeClusterSecretSt{}
	mi := &file_kusec_v1_kube_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeClusterSecretSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeClusterSecretSt) ProtoMessage() {}

func (x *KubeClusterSecretSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeClusterSecretSt.ProtoReflect.Descriptor instead.
func (*KubeClusterSecretSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{2}
}

func (x *KubeClusterSecretSt) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeClusterSecretSt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeClusterSecretSt) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KubeClusterSecretSt) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KubeClusterSecretSt) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

type KubeListClusterSecretsRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false — сервис запущен вне кластера (secrets тогда пуст).
	InCluster     bool                   `protobuf:"varint,1,opt,name=in_cluster,json=inCluster,proto3" json:"in_cluster,omitempty"`
	Secrets       []*KubeClusterSecretSt `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeListClusterSecretsRep) Reset() {
	*x = KubeListClusterSecretsRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeListClusterSecretsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeListClusterSecretsRep) ProtoMessage() {}

func (x *KubeListClusterSecretsRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeListClusterSecretsRep.ProtoReflect.Descriptor instead.
func (*KubeListClusterSecretsRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{3}
}

func (x *KubeListClusterSecretsRep) GetInCluster() bool {
	if x != nil {
		return x.InCluster
	}
	return false
}

func (x *KubeListClusterSecretsRep) GetSecrets() []*KubeClusterSecretSt {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type KubeImportSecretReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Целевое приложение, в которое импортируется секрет.
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Секрет-источник в кластере.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Имя посадочного секрета kusec (slug). Обязательно.
	SecretSlug    string `protobuf:"bytes,4,opt,name=secret_slug,json=secretSlug,proto3" json:"secret_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeImportSecretReq) Reset() {
	*x = KubeImportSecretReq{}
	mi := &file_kusec_v1_kube_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeImportSecretReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeImportSecretReq) ProtoMessage() {}

func (x *KubeImportSecretReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeImportSecretReq.ProtoReflect.Descriptor instead.
func (*KubeImportSecretReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{4}
}

func (x *KubeImportSecretReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *KubeImportSecretReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeImportSecretReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeImportSecretReq) GetSecretSlug() string {
	if x != nil {
		return x.SecretSlug
	}
	return ""
}

type KubeImportSecretRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Запись secret (созданная или дозаполненная).
	SecretId string `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	// Фактический slug посадочного секрета.
	SecretSlug string `protobuf:"bytes,2,opt,name=secret_slug,json=secretSlug,proto3" json:"secret_slug,omitempty"`
	// false — секрет уже существовал, выполнено дозаполнение.
	SecretCreated bool `protobuf:"varint,3,opt,name=secret_created,json=secretCreated,proto3" json:"secret_created,omitempty"`
	// Сколько item-ов создано (новые ключи).
	CreatedItems int64 `protobuf:"varint,4,opt,name=created_items,json=createdItems,proto3" json:"created_items,omitempty"`
	// Сколько item-ов обновлено (совпавшие ключи — значение перезаписано).
	UpdatedItems  int64 `protobuf:"varint,5,opt,name=updated_items,json=updatedItems,proto3" json:"updated_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeImportSecretRep) Reset() {
	*x = KubeImportSecretRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeImportSecretRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeImportSecretRep) ProtoMessage() {}

func (x *KubeImportSecretRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeImportSecretRep.ProtoReflect.Descriptor instead.
func (*KubeImportSecretRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{5}
}

func (x *KubeImportSecretRep) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *KubeImportSecretRep) GetSecretSlug() string {
	if x != nil {
		return x.SecretSlug
	}
	return ""
}

func (x *KubeImportSecretRep) GetSecretCreated() bool {
	if x != nil {
		return x.SecretCreated
	}
	return false
}

func (x *KubeImportSecretRep) GetCreatedItems() int64 {
	if x != nil {
		return x.CreatedItems
	}
	return 0
}

func (x *KubeImportSecretRep) GetUpdatedItems() int64 {
	if x != nil {
		return x.UpdatedItems
	}
	return 0
}

type KubeSyncSecretsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncSecretsReq) Reset() {
	*x = KubeSyncSecretsReq{}
	mi := &file_kusec_v1_kube_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncSecretsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncSecretsReq) ProtoMessage() {}

func (x *KubeSyncSecretsReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncSecretsReq.ProtoReflect.Descriptor instead.
func (*KubeSyncSecretsReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{6}
}

func (x *KubeSyncSecretsReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type KubeSyncSecretsRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Списки в формате "namespace/name".
	Created   []string `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	Updated   []string `protobuf:"bytes,2,rep,name=updated,proto3" json:"updated,omitempty"`
	Deleted   []string `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"`
	Unchanged int64    `protobuf:"varint,4,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	// Ошибки по отдельным секретам (sync продолжается для остальных).
	Errors        []string `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncSecretsRep) Reset() {
	*x = KubeSyncSecretsRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncSecretsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncSecretsRep) ProtoMessage() {}

func (x *KubeSyncSecretsRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncSecretsRep.ProtoReflect.Descriptor instead.
func (*KubeSyncSecretsRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{7}
}

func (x *KubeSyncSecretsRep) GetCreated() []string {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *KubeSyncSecretsRep) GetUpdated() []string {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *KubeSyncSecretsRep) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *KubeSyncSecretsRep) GetUnchanged() int64 {
	if x != nil {
		return x.Unchanged
	}
	return 0
}

func (x *KubeSyncSecretsRep) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type KubeSyncConfigMapsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncConfigMapsReq) Reset() {
	*x = KubeSyncConfigMapsReq{}
	mi := &file_kusec_v1_kube_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncConfigMapsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncConfigMapsReq) ProtoMessage() {}

func (x *KubeSyncConfigMapsReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncConfigMapsReq.ProtoReflect.Descriptor instead.
func (*KubeSyncConfigMapsReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{8}
}

func (x *KubeSyncConfigMapsReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type KubeSyncConfigMapsRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Списки в формате "namespace/name".
	Created   []string `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	Updated   []string `protobuf:"bytes,2,rep,name=updated,proto3" json:"updated,omitempty"`
	Deleted   []string `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"`
	Unchanged int64    `protobuf:"varint,4,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	// Ошибки по отдельным configmap-ам (sync продолжается для остальных).
	Errors        []string `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncConfigMapsRep) Reset() {
	*x = KubeSyncConfigMapsRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncConfigMapsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncConfigMapsRep) ProtoMessage() {}

func (x *KubeSyncConfigMapsRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncConfigMapsRep.ProtoReflect.Descriptor instead.
func (*KubeSyncConfigMapsRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{9}
}

func (x *KubeSyncConfigMapsRep) GetCreated() []string {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *KubeSyncConfigMapsRep) GetUpdated() []string {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *KubeSyncConfigMapsRep) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *KubeSyncConfigMapsRep) GetUnchanged() int64 {
	if x != nil {
		return x.Unchanged
	}
	return 0
}

func (x *KubeSyncConfigMapsRep) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type KubeSyncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncReq) Reset() {
	*x = KubeSyncReq{}
	mi := &file_kusec_v1_kube_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncReq) ProtoMessage() {}

func (x *KubeSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncReq.ProtoReflect.Descriptor instead.
func (*KubeSyncReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{10}
}

func (x *KubeSyncReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type KubeSyncRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Результат синхронизации секретов.
	Secrets *KubeSyncSecretsRep `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	// Результат синхронизации configmap-ов.
	Configmaps    *KubeSyncConfigMapsRep `protobuf:"bytes,2,opt,name=configmaps,proto3" json:"configmaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeSyncRep) Reset() {
	*x = KubeSyncRep{}
	mi := &file_kusec_v1_kube_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSyncRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSyncRep) ProtoMessage() {}

func (x *KubeSyncRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_kube_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSyncRep.ProtoReflect.Descriptor instead.
func (*KubeSyncRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_kube_proto_rawDescGZIP(), []int{11}
}

func (x *KubeSyncRep) GetSecrets() *KubeSyncSecretsRep {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *KubeSyncRep) GetConfigmaps() *KubeSyncConfigMapsRep {
	if x != nil {
		return x.Configmaps
	}
	return nil
}

var File_kusec_v1_kube_proto protoreflect.FileDescriptor

const file_kusec_v1_kube_proto_rawDesc = "" +
	"\n" +
	"\x13kusec_v1/kube.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"V\n" +
	"\x15KubeListNamespacesRep\x12\x1d\n" +
	"\n" +
	"in_cluster\x18\x01 \x01(\bR\tinCluster\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\"9\n" +
	"\x19KubeListClusterSecretsReq\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x89\x01\n" +
	"\x13KubeClusterSecretSt\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\tR\x04keys\x12\x18\n" +
	"\amanaged\x18\x05 \x01(\bR\amanaged\"s\n" +
	"\x19KubeListClusterSecretsRep\x12\x1d\n" +
	"\n" +
	"in_cluster\x18\x01 \x01(\bR\tinCluster\x127\n" +
	"\asecrets\x18\x02 \x03(\v2\x1d.kusec_v1.KubeClusterSecretStR\asecrets\"\x7f\n" +
	"\x13KubeImportSecretReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vsecret_slug\x18\x04 \x01(\tR\n" +
	"secretSlug\"\xc4\x01\n" +
	"\x13KubeImportSecretRep\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x1f\n" +
	"\vsecret_slug\x18\x02 \x01(\tR\n" +
	"secretSlug\x12%\n" +
	"\x0esecret_created\x18\x03 \x01(\bR\rsecretCreated\x12#\n" +
	"\rcreated_items\x18\x04 \x01(\x03R\fcreatedItems\x12#\n" +
	"\rupdated_items\x18\x05 \x01(\x03R\fupdatedItems\"+\n" +
	"\x12KubeSyncSecretsReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x98\x01\n" +
	"\x12KubeSyncSecretsRep\x12\x18\n" +
	"\acreated\x18\x01 \x03(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x03(\tR\aupdated\x12\x18\n" +
	"\adeleted\x18\x03 \x03(\tR\adeleted\x12\x1c\n" +
	"\tunchanged\x18\x04 \x01(\x03R\tunchanged\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\".\n" +
	"\x15KubeSyncConfigMapsReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x9b\x01\n" +
	"\x15KubeSyncConfigMapsRep\x12\x18\n" +
	"\acreated\x18\x01 \x03(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x03(\tR\aupdated\x12\x18\n" +
	"\adeleted\x18\x03 \x03(\tR\adeleted\x12\x1c\n" +
	"\tunchanged\x18\x04 \x01(\x03R\tunchanged\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\"$\n" +
	"\vKubeSyncReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x86\x01\n" +
	"\vKubeSyncRep\x126\n" +
	"\asecrets\x18\x01 \x01(\v2\x1c.kusec_v1.KubeSyncSecretsRepR\asecrets\x12?\n" +
	"\n" +
	"configmaps\x18\x02 \x01(\v2\x1f.kusec_v1.KubeSyncConfigMapsRepR\n" +
	"configmaps2\x81\x05\n" +
	"\x04Kube\x12g\n" +
	"\vSyncSecrets\x12\x1c.kusec_v1.KubeSyncSecretsReq\x1a\x1c.kusec_v1.KubeSyncSecretsRep\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/kube/sync-secret\x12s\n" +
	"\x0eSyncConfigMaps\x12\x1f.kusec_v1.KubeSyncConfigMapsReq\x1a\x1f.kusec_v1.KubeSyncConfigMapsRep\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/kube/sync-configmap\x12K\n" +
	"\x04Sync\x12\x15.kusec_v1.KubeSyncReq\x1a\x15.kusec_v1.KubeSyncRep\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/kube/sync\x12b\n" +
	"\x0eListNamespaces\x12\x16.google.protobuf.Empty\x1a\x1f.kusec_v1.KubeListNamespacesRep\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/kube/namespace\x12|\n" +
	"\x12ListClusterSecrets\x12#.kusec_v1.KubeListClusterSecretsReq\x1a#.kusec_v1.KubeListClusterSecretsRep\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/kube/cluster-secret\x12l\n" +
	"\fImportSecret\x12\x1d.kusec_v1.KubeImportSecretReq\x1a\x1d.kusec_v1.KubeImportSecretRep\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/kube/import-secretB\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_kube_proto_rawDescOnce sync.Once
	file_kusec_v1_kube_proto_rawDescData []byte
)

func file_kusec_v1_kube_proto_rawDescGZIP() []byte {
	file_kusec_v1_kube_proto_rawDescOnce.Do(func() {
		file_kusec_v1_kube_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_kube_proto_rawDesc), len(file_kusec_v1_kube_proto_rawDesc)))
	})
	return file_kusec_v1_kube_proto_rawDescData
}

var file_kusec_v1_kube_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kusec_v1_kube_proto_goTypes = []any{
	(*KubeListNamespacesRep)(nil),     // 0: kusec_v1.KubeListNamespacesRep
	(*KubeListClusterSecretsReq)(nil), // 1: kusec_v1.KubeListClusterSecretsReq
	(*KubeClusterSecretSt)(nil),       // 2: kusec_v1.KubeClusterSecretSt
	(*KubeListClusterSecretsRep)(nil), // 3: kusec_v1.KubeListClusterSecretsRep
	(*KubeImportSecretReq)(nil),       // 4: kusec_v1.KubeImportSecretReq
	(*KubeImportSecretRep)(nil),       // 5: kusec_v1.KubeImportSecretRep
	(*KubeSyncSecretsReq)(nil),        // 6: kusec_v1.KubeSyncSecretsReq
	(*KubeSyncSecretsRep)(nil),        // 7: kusec_v1.KubeSyncSecretsRep
	(*KubeSyncConfigMapsReq)(nil),     // 8: kusec_v1.KubeSyncConfigMapsReq
	(*KubeSyncConfigMapsRep)(nil),     // 9: kusec_v1.KubeSyncConfigMapsRep
	(*KubeSyncReq)(nil),               // 10: kusec_v1.KubeSyncReq
	(*KubeSyncRep)(nil),               // 11: kusec_v1.KubeSyncRep
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
}
var file_kusec_v1_kube_proto_depIdxs = []int32{
	2,  // 0: kusec_v1.KubeListClusterSecretsRep.secrets:type_name -> kusec_v1.KubeClusterSecretSt
	7,  // 1: kusec_v1.KubeSyncRep.secrets:type_name -> kusec_v1.KubeSyncSecretsRep
	9,  // 2: kusec_v1.KubeSyncRep.configmaps:type_name -> kusec_v1.KubeSyncConfigMapsRep
	6,  // 3: kusec_v1.Kube.SyncSecrets:input_type -> kusec_v1.KubeSyncSecretsReq
	8,  // 4: kusec_v1.Kube.SyncConfigMaps:input_type -> kusec_v1.KubeSyncConfigMapsReq
	10, // 5: kusec_v1.Kube.Sync:input_type -> kusec_v1.KubeSyncReq
	12, // 6: kusec_v1.Kube.ListNamespaces:input_type -> google.protobuf.Empty
	1,  // 7: kusec_v1.Kube.ListClusterSecrets:input_type -> kusec_v1.KubeListClusterSecretsReq
	4,  // 8: kusec_v1.Kube.ImportSecret:input_type -> kusec_v1.KubeImportSecretReq
	7,  // 9: kusec_v1.Kube.SyncSecrets:output_type -> kusec_v1.KubeSyncSecretsRep
	9,  // 10: kusec_v1.Kube.SyncConfigMaps:output_type -> kusec_v1.KubeSyncConfigMapsRep
	11, // 11: kusec_v1.Kube.Sync:output_type -> kusec_v1.KubeSyncRep
	0,  // 12: kusec_v1.Kube.ListNamespaces:output_type -> kusec_v1.KubeListNamespacesRep
	3,  // 13: kusec_v1.Kube.ListClusterSecrets:output_type -> kusec_v1.KubeListClusterSecretsRep
	5,  // 14: kusec_v1.Kube.ImportSecret:output_type -> kusec_v1.KubeImportSecretRep
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kusec_v1_kube_proto_init() }
func file_kusec_v1_kube_proto_init() {
	if File_kusec_v1_kube_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_kube_proto_rawDesc), len(file_kusec_v1_kube_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_kube_proto_goTypes,
		DependencyIndexes: file_kusec_v1_kube_proto_depIdxs,
		MessageInfos:      file_kusec_v1_kube_proto_msgTypes,
	}.Build()
	File_kusec_v1_kube_proto = out.File
	file_kusec_v1_kube_proto_goTypes = nil
	file_kusec_v1_kube_proto_depIdxs = nil
}
