// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: kusec_v1/kube.proto

package kusec_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kube_SyncSecrets_FullMethodName        = "/kusec_v1.Kube/SyncSecrets"
	Kube_SyncConfigMaps_FullMethodName     = "/kusec_v1.Kube/SyncConfigMaps"
	Kube_Sync_FullMethodName               = "/kusec_v1.Kube/Sync"
	Kube_ListNamespaces_FullMethodName     = "/kusec_v1.Kube/ListNamespaces"
	Kube_ListClusterSecrets_FullMethodName = "/kusec_v1.Kube/ListClusterSecrets"
	Kube_ImportSecret_FullMethodName       = "/kusec_v1.Kube/ImportSecret"
)

// KubeClient is the client API for Kube service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Синхронизация секретов из базы в Kubernetes (только изнутри кластера).
// Имя k8s-секрета: {KUBE_SECRET_NAME_PREFIX}{app.slug_name}-{secret.slug_name}
// (префикс из env, по умолчанию "kusec-"), namespace — из app.
// Управляемые секреты помечаются лейблом app.kubernetes.io/managed-by=kusec;
// удаляются только они.
type KubeClient interface {
	SyncSecrets(ctx context.Context, in *KubeSyncSecretsReq, opts ...grpc.CallOption) (*KubeSyncSecretsRep, error)
	// Синхронизация configmap-ов из базы в Kubernetes (только изнутри кластера).
	// Имя k8s-configmap: {KUBE_SECRET_NAME_PREFIX}{app.slug_name}-{configmap.slug_name}.
	// Управляемые configmap-ы помечаются лейблом app.kubernetes.io/managed-by=kusec.
	SyncConfigMaps(ctx context.Context, in *KubeSyncConfigMapsReq, opts ...grpc.CallOption) (*KubeSyncConfigMapsRep, error)
	// Общая синхронизация: и секреты, и configmap-ы за один вызов под единой
	// блокировкой (только изнутри кластера).
	Sync(ctx context.Context, in *KubeSyncReq, opts ...grpc.CallOption) (*KubeSyncRep, error)
	ListNamespaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*KubeListNamespacesRep, error)
	// Список секретов кластера для выбора при импорте (только админ).
	// namespace в query пуст — берутся все namespace-ы без системных kube-*.
	ListClusterSecrets(ctx context.Context, in *KubeListClusterSecretsReq, opts ...grpc.CallOption) (*KubeListClusterSecretsRep, error)
	// Импорт одного секрета кластера в указанное приложение (только админ).
	// Секрет кластера становится записью secret в app_id с item-ами по ключам
	// data. Имя посадочного секрета (slug) обязательно. Если секрет с таким slug
	// в приложении уже есть — выполняется дозаполнение: недостающие ключи
	// создаются, совпавшие — перезаписываются значением из кластера. Источник в
	// кластере не меняется.
	ImportSecret(ctx context.Context, in *KubeImportSecretReq, opts ...grpc.CallOption) (*KubeImportSecretRep, error)
}

type kubeClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeClient(cc grpc.ClientConnInterface) KubeClient {
	return &kubeClient{cc}
}

func (c *kubeClient) SyncSecrets(ctx context.Context, in *KubeSyncSecretsReq, opts ...grpc.CallOption) (*KubeSyncSecretsRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeSyncSecretsRep)
	err := c.cc.Invoke(ctx, Kube_SyncSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeClient) SyncConfigMaps(ctx context.Context, in *KubeSyncConfigMapsReq, opts ...grpc.CallOption) (*KubeSyncConfigMapsRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeSyncConfigMapsRep)
	err := c.cc.Invoke(ctx, Kube_SyncConfigMaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeClient) Sync(ctx context.Context, in *KubeSyncReq, opts ...grpc.CallOption) (*KubeSyncRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeSyncRep)
	err := c.cc.Invoke(ctx, Kube_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeClient) ListNamespaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*KubeListNamespacesRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeListNamespacesRep)
	err := c.cc.Invoke(ctx, Kube_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeClient) ListClusterSecrets(ctx context.Context, in *KubeListClusterSecretsReq, opts ...grpc.CallOption) (*KubeListClusterSecretsRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeListClusterSecretsRep)
	err := c.cc.Invoke(ctx, Kube_ListClusterSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeClient) ImportSecret(ctx context.Context, in *KubeImportSecretReq, opts ...grpc.CallOption) (*KubeImportSecretRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeImportSecretRep)
	err := c.cc.Invoke(ctx, Kube_ImportSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeServer is the server API for Kube service.
// All implementations must embed UnimplementedKubeServer
// for forward compatibility.
//
// Синхронизация секретов из базы в Kubernetes (только изнутри кластера).
// Имя k8s-секрета: {KUBE_SECRET_NAME_PREFIX}{app.slug_name}-{secret.slug_name}
// (префикс из env, по умолчанию "kusec-"), namespace — из app.
// Управляемые секреты помечаются лейблом app.kubernetes.io/managed-by=kusec;
// удаляются только они.
type KubeServer interface {
	SyncSecrets(context.Context, *KubeSyncSecretsReq) (*KubeSyncSecretsRep, error)
	// Синхронизация configmap-ов из базы в Kubernetes (только изнутри кластера).
	// Имя k8s-configmap: {KUBE_SECRET_NAME_PREFIX}{app.slug_name}-{configmap.slug_name}.
	// Управляемые configmap-ы помечаются лейблом app.kubernetes.io/managed-by=kusec.
	SyncConfigMaps(context.Context, *KubeSyncConfigMapsReq) (*KubeSyncConfigMapsRep, error)
	// Общая синхронизация: и секреты, и configmap-ы за один вызов под единой
	// блокировкой (только изнутри кластера).
	Sync(context.Context, *KubeSyncReq) (*KubeSyncRep, error)
	ListNamespaces(context.Context, *emptypb.Empty) (*KubeListNamespacesRep, error)
	// Список секретов кластера для выбора при импорте (только админ).
	// namespace в query пуст — берутся все namespace-ы без системных kube-*.
	ListClusterSecrets(context.Context, *KubeListClusterSecretsReq) (*KubeListClusterSecretsRep, error)
	// Импорт одного секрета кластера в указанное приложение (только админ).
	// Секрет кластера становится записью secret в app_id с item-ами по ключам
	// data. Имя посадочного секрета (slug) обязательно. Если секрет с таким slug
	// в приложении уже есть — выполняется дозаполнение: недостающие ключи
	// создаются, совпавшие — перезаписываются значением из кластера. Источник в
	// кластере не меняется.
	ImportSecret(context.Context, *KubeImportSecretReq) (*KubeImportSecretRep, error)
	mustEmbedUnimplementedKubeServer()
}

// UnimplementedKubeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubeServer struct{}

func (UnimplementedKubeServer) SyncSecrets(context.Context, *KubeSyncSecretsReq) (*KubeSyncSecretsRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncSecrets not implemented")
}
func (UnimplementedKubeServer) SyncConfigMaps(context.Context, *KubeSyncConfigMapsReq) (*KubeSyncConfigMapsRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncConfigMaps not implemented")
}
func (UnimplementedKubeServer) Sync(context.Context, *KubeSyncReq) (*KubeSyncRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedKubeServer) ListNamespaces(context.Context, *emptypb.Empty) (*KubeListNamespacesRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedKubeServer) ListClusterSecrets(context.Context, *KubeListClusterSecretsReq) (*KubeListClusterSecretsRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClusterSecrets not implemented")
}
func (UnimplementedKubeServer) ImportSecret(context.Context, *KubeImportSecretReq) (*KubeImportSecretRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSecret not implemented")
}
func (UnimplementedKubeServer) mustEmbedUnimplementedKubeServer() {}
func (UnimplementedKubeServer) testEmbeddedByValue()              {}

// UnsafeKubeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeServer will
// result in compilation errors.
type UnsafeKubeServer interface {
	mustEmbedUnimplementedKubeServer()
}

func RegisterKubeServer(s grpc.ServiceRegistrar, srv KubeServer) {
	// If the following call pancis, it indicates UnimplementedKubeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kube_ServiceDesc, srv)
}

func _Kube_SyncSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeSyncSecretsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeServer).SyncSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kube_SyncSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeServer).SyncSecrets(ctx, req.(*KubeSyncSecretsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kube_SyncConfigMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeSyncConfigMapsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeServer).SyncConfigMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kube_SyncConfigMaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeServer).SyncConfigMaps(ctx, req.(*KubeSyncConfigMapsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kube_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeSyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kube_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeServer).Sync(ctx, req.(*KubeSyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kube_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kube_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeServer).ListNamespaces(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kube_ListClusterSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeListClusterSecretsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeServer).ListClusterSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kube_ListClusterSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeServer).ListClusterSecrets(ctx, req.(*KubeListClusterSecretsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kube_ImportSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeImportSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeServer).ImportSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kube_ImportSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeServer).ImportSecret(ctx, req.(*KubeImportSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Kube_ServiceDesc is the grpc.ServiceDesc for Kube service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kube_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kusec_v1.Kube",
	HandlerType: (*KubeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncSecrets",
			Handler:    _Kube_SyncSecrets_Handler,
		},
		{
			MethodName: "SyncConfigMaps",
			Handler:    _Kube_SyncConfigMaps_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _Kube_Sync_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _Kube_ListNamespaces_Handler,
		},
		{
			MethodName: "ListClusterSecrets",
			Handler:    _Kube_ListClusterSecrets_Handler,
		},
		{
			MethodName: "ImportSecret",
			Handler:    _Kube_ImportSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kusec_v1/kube.proto",
}
