// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: kusec_v1/secret.proto

package kusec_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Secret_List_FullMethodName   = "/kusec_v1.Secret/List"
	Secret_Get_FullMethodName    = "/kusec_v1.Secret/Get"
	Secret_Create_FullMethodName = "/kusec_v1.Secret/Create"
	Secret_Update_FullMethodName = "/kusec_v1.Secret/Update"
	Secret_Delete_FullMethodName = "/kusec_v1.Secret/Delete"
)

// SecretClient is the client API for Secret service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecretClient interface {
	List(ctx context.Context, in *SecretListReq, opts ...grpc.CallOption) (*SecretListRep, error)
	Get(ctx context.Context, in *SecretGetReq, opts ...grpc.CallOption) (*SecretMain, error)
	Create(ctx context.Context, in *SecretCreateReq, opts ...grpc.CallOption) (*SecretCreateRep, error)
	Update(ctx context.Context, in *SecretUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *SecretGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type secretClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretClient(cc grpc.ClientConnInterface) SecretClient {
	return &secretClient{cc}
}

func (c *secretClient) List(ctx context.Context, in *SecretListReq, opts ...grpc.CallOption) (*SecretListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretListRep)
	err := c.cc.Invoke(ctx, Secret_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretClient) Get(ctx context.Context, in *SecretGetReq, opts ...grpc.CallOption) (*SecretMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretMain)
	err := c.cc.Invoke(ctx, Secret_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretClient) Create(ctx context.Context, in *SecretCreateReq, opts ...grpc.CallOption) (*SecretCreateRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretCreateRep)
	err := c.cc.Invoke(ctx, Secret_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretClient) Update(ctx context.Context, in *SecretUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Secret_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretClient) Delete(ctx context.Context, in *SecretGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Secret_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServer is the server API for Secret service.
// All implementations must embed UnimplementedSecretServer
// for forward compatibility.
type SecretServer interface {
	List(context.Context, *SecretListReq) (*SecretListRep, error)
	Get(context.Context, *SecretGetReq) (*SecretMain, error)
	Create(context.Context, *SecretCreateReq) (*SecretCreateRep, error)
	Update(context.Context, *SecretUpdateReq) (*emptypb.Empty, error)
	Delete(context.Context, *SecretGetReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedSecretServer()
}

// UnimplementedSecretServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretServer struct{}

func (UnimplementedSecretServer) List(context.Context, *SecretListReq) (*SecretListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSecretServer) Get(context.Context, *SecretGetReq) (*SecretMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSecretServer) Create(context.Context, *SecretCreateReq) (*SecretCreateRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSecretServer) Update(context.Context, *SecretUpdateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSecretServer) Delete(context.Context, *SecretGetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSecretServer) mustEmbedUnimplementedSecretServer() {}
func (UnimplementedSecretServer) testEmbeddedByValue()                {}

// UnsafeSecretServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretServer will
// result in compilation errors.
type UnsafeSecretServer interface {
	mustEmbedUnimplementedSecretServer()
}

func RegisterSecretServer(s grpc.ServiceRegistrar, srv SecretServer) {
	// If the following call pancis, it indicates UnimplementedSecretServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Secret_ServiceDesc, srv)
}

func _Secret_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secret_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServer).List(ctx, req.(*SecretListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secret_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secret_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServer).Get(ctx, req.(*SecretGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secret_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secret_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServer).Create(ctx, req.(*SecretCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secret_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secret_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServer).Update(ctx, req.(*SecretUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secret_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secret_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServer).Delete(ctx, req.(*SecretGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Secret_ServiceDesc is the grpc.ServiceDesc for Secret service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Secret_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kusec_v1.Secret",
	HandlerType: (*SecretServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Secret_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Secret_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Secret_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Secret_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Secret_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kusec_v1/secret.proto",
}
