// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/syncrun.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Затронутый k8s-объект запуска.
type SyncRunObjectSt struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Secret | ConfigMap
	KubeKind string `protobuf:"bytes,2,opt,name=kube_kind,json=kubeKind,proto3" json:"kube_kind,omitempty"`
	KubeName string `protobuf:"bytes,3,opt,name=kube_name,json=kubeName,proto3" json:"kube_name,omitempty"`
	// created | updated | deleted | unchanged | error
	Op    string `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// HMAC-отпечаток содержимого объекта (сопоставим с аннотацией
	// kusec.io/content-hash на объекте кластера)
	ContentHash string `protobuf:"bytes,6,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// имена ключей с изменившимся значением (для created/deleted — все ключи)
	ChangedKeys   []string `protobuf:"bytes,7,rep,name=changed_keys,json=changedKeys,proto3" json:"changed_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRunObjectSt) Reset() {
	*x = SyncRunObjectSt{}
	mi := &file_kusec_v1_syncrun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRunObjectSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRunObjectSt) ProtoMessage() {}

func (x *SyncRunObjectSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_syncrun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRunObjectSt.ProtoReflect.Descriptor instead.
func (*SyncRunObjectSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_syncrun_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRunObjectSt) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SyncRunObjectSt) GetKubeKind() string {
	if x != nil {
		return x.KubeKind
	}
	return ""
}

func (x *SyncRunObjectSt) GetKubeName() string {
	if x != nil {
		return x.KubeName
	}
	return ""
}

func (x *SyncRunObjectSt) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *SyncRunObjectSt) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncRunObjectSt) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *SyncRunObjectSt) GetChangedKeys() []string {
	if x != nil {
		return x.ChangedKeys
	}
	return nil
}

type SyncRunMain struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	// running | ok | partial | error
	Status        string  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string  `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ActorUsrId    *int64  `protobuf:"varint,6,opt,name=actor_usr_id,json=actorUsrId,proto3,oneof" json:"actor_usr_id,omitempty"`
	ActorApiKeyId *string `protobuf:"bytes,7,opt,name=actor_api_key_id,json=actorApiKeyId,proto3,oneof" json:"actor_api_key_id,omitempty"`
	ActorName     string  `protobuf:"bytes,8,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	// ui | api | mcp | system
	Source    string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	RequestId string `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// null — sync всех доступных app
	AppId      *string `protobuf:"bytes,11,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	DurationMs int64   `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// затронутые объекты; заполняется только в Get
	Objects       []*SyncRunObjectSt `protobuf:"bytes,13,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRunMain) Reset() {
	*x = SyncRunMain{}
	mi := &file_kusec_v1_syncrun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRunMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRunMain) ProtoMessage() {}

func (x *SyncRunMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_syncrun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRunMain.ProtoReflect.Descriptor instead.
func (*SyncRunMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_syncrun_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRunMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncRunMain) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SyncRunMain) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *SyncRunMain) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncRunMain) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncRunMain) GetActorUsrId() int64 {
	if x != nil && x.ActorUsrId != nil {
		return *x.ActorUsrId
	}
	return 0
}

func (x *SyncRunMain) GetActorApiKeyId() string {
	if x != nil && x.ActorApiKeyId != nil {
		return *x.ActorApiKeyId
	}
	return ""
}

func (x *SyncRunMain) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *SyncRunMain) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SyncRunMain) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncRunMain) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *SyncRunMain) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SyncRunMain) GetObjects() []*SyncRunObjectSt {
	if x != nil {
		return x.Objects
	}
	return nil
}

type SyncRunListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page с 0, page_size обязателен (≤ 100); сортировка по умолчанию
	// -started_at (новые первыми).
	ListParams *ListParamsSt `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	AppId      *string       `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	// запуски, затронувшие объекты этого namespace
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	StartedAtGte  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at_gte,json=startedAtGte,proto3,oneof" json:"started_at_gte,omitempty"`
	StartedAtLt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at_lt,json=startedAtLt,proto3,oneof" json:"started_at_lt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRunListReq) Reset() {
	*x = SyncRunListReq{}
	mi := &file_kusec_v1_syncrun_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRunListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRunListReq) ProtoMessage() {}

func (x *SyncRunListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_syncrun_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRunListReq.ProtoReflect.Descriptor instead.
func (*SyncRunListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_syncrun_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRunListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *SyncRunListReq) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *SyncRunListReq) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *SyncRunListReq) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *SyncRunListReq) GetStartedAtGte() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAtGte
	}
	return nil
}

func (x *SyncRunListReq) GetStartedAtLt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAtLt
	}
	return nil
}

type SyncRunListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*SyncRunMain         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRunListRep) Reset() {
	*x = SyncRunListRep{}
	mi := &file_kusec_v1_syncrun_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRunListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRunListRep) ProtoMessage() {}

func (x *SyncRunListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_syncrun_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRunListRep.ProtoReflect.Descriptor instead.
func (*SyncRunListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_syncrun_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRunListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *SyncRunListRep) GetResults() []*SyncRunMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type SyncRunGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRunGetReq) Reset() {
	*x = SyncRunGetReq{}
	mi := &file_kusec_v1_syncrun_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRunGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRunGetReq) ProtoMessage() {}

func (x *SyncRunGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_syncrun_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRunGetReq.ProtoReflect.Descriptor instead.
func (*SyncRunGetReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_syncrun_proto_rawDescGZIP(), []int{4}
}

func (x *SyncRunGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_kusec_v1_syncrun_proto protoreflect.FileDescriptor

const file_kusec_v1_syncrun_proto_rawDesc = "" +
	"\n" +
	"\x16kusec_v1/syncrun.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15kusec_v1/common.proto\"\xd5\x01\n" +
	"\x0fSyncRunObjectSt\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tkube_kind\x18\x02 \x01(\tR\bkubeKind\x12\x1b\n" +
	"\tkube_name\x18\x03 \x01(\tR\bkubeName\x12\x0e\n" +
	"\x02op\x18\x04 \x01(\tR\x02op\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12!\n" +
	"\fcontent_hash\x18\x06 \x01(\tR\vcontentHash\x12!\n" +
	"\fchanged_keys\x18\a \x03(\tR\vchangedKeys\"\xa6\x04\n" +
	"\vSyncRunMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12@\n" +
	"\vfinished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"finishedAt\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12%\n" +
	"\factor_usr_id\x18\x06 \x01(\x03H\x01R\n" +
	"actorUsrId\x88\x01\x01\x12,\n" +
	"\x10actor_api_key_id\x18\a \x01(\tH\x02R\ractorApiKeyId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"actor_name\x18\b \x01(\tR\tactorName\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x12\x1a\n" +
	"\x06app_id\x18\v \x01(\tH\x03R\x05appId\x88\x01\x01\x12\x1f\n" +
	"\vduration_ms\x18\f \x01(\x03R\n" +
	"durationMs\x123\n" +
	"\aobjects\x18\r \x03(\v2\x19.kusec_v1.SyncRunObjectStR\aobjectsB\x0e\n" +
	"\f_finished_atB\x0f\n" +
	"\r_actor_usr_idB\x13\n" +
	"\x11_actor_api_key_idB\t\n" +
	"\a_app_id\"\xfa\x02\n" +
	"\x0eSyncRunListReq\x127\n" +
	"\vlist_params\x18\x01 \x01(\v2\x16.kusec_v1.ListParamsStR\n" +
	"listParams\x12\x1a\n" +
	"\x06app_id\x18\x02 \x01(\tH\x00R\x05appId\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x01R\tnamespace\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x02R\x06status\x88\x01\x01\x12E\n" +
	"\x0estarted_at_gte\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\fstartedAtGte\x88\x01\x01\x12C\n" +
	"\rstarted_at_lt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vstartedAtLt\x88\x01\x01B\t\n" +
	"\a_app_idB\f\n" +
	"\n" +
	"_namespaceB\t\n" +
	"\a_statusB\x11\n" +
	"\x0f_started_at_gteB\x10\n" +
	"\x0e_started_at_lt\"\x86\x01\n" +
	"\x0eSyncRunListRep\x12C\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x1a.kusec_v1.PaginationInfoStR\x0epaginationInfo\x12/\n" +
	"\aresults\x18\x02 \x03(\v2\x15.kusec_v1.SyncRunMainR\aresults\"\x1f\n" +
	"\rSyncRunGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xa7\x01\n" +
	"\aSyncRun\x12M\n" +
	"\x04List\x12\x18.kusec_v1.SyncRunListReq\x1a\x18.kusec_v1.SyncRunListRep\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/sync-run\x12M\n" +
	"\x03Get\x12\x17.kusec_v1.SyncRunGetReq\x1a\x15.kusec_v1.SyncRunMain\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/sync-run/{id}B\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_syncrun_proto_rawDescOnce sync.Once
	file_kusec_v1_syncrun_proto_rawDescData []byte
)

func file_kusec_v1_syncrun_proto_rawDescGZIP() []byte {
	file_kusec_v1_syncrun_proto_rawDescOnce.Do(func() {
		file_kusec_v1_syncrun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_syncrun_proto_rawDesc), len(file_kusec_v1_syncrun_proto_rawDesc)))
	})
	return file_kusec_v1_syncrun_proto_rawDescData
}

var file_kusec_v1_syncrun_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kusec_v1_syncrun_proto_goTypes = []any{
	(*SyncRunObjectSt)(nil),       // 0: kusec_v1.SyncRunObjectSt
	(*SyncRunMain)(nil),           // 1: kusec_v1.SyncRunMain
	(*SyncRunListReq)(nil),        // 2: kusec_v1.SyncRunListReq
	(*SyncRunListRep)(nil),        // 3: kusec_v1.SyncRunListRep
	(*SyncRunGetReq)(nil),         // 4: kusec_v1.SyncRunGetReq
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*ListParamsSt)(nil),          // 6: kusec_v1.ListParamsSt
	(*PaginationInfoSt)(nil),      // 7: kusec_v1.PaginationInfoSt
}
var file_kusec_v1_syncrun_proto_depIdxs = []int32{
	5,  // 0: kusec_v1.SyncRunMain.started_at:type_name -> google.protobuf.Timestamp
	5,  // 1: kusec_v1.SyncRunMain.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 2: kusec_v1.SyncRunMain.objects:type_name -> kusec_v1.SyncRunObjectSt
	6,  // 3: kusec_v1.SyncRunListReq.list_params:type_name -> kusec_v1.ListParamsSt
	5,  // 4: kusec_v1.SyncRunListReq.started_at_gte:type_name -> google.protobuf.Timestamp
	5,  // 5: kusec_v1.SyncRunListReq.started_at_lt:type_name -> google.protobuf.Timestamp
	7,  // 6: kusec_v1.SyncRunListRep.pagination_info:type_name -> kusec_v1.PaginationInfoSt
	1,  // 7: kusec_v1.SyncRunListRep.results:type_name -> kusec_v1.SyncRunMain
	2,  // 8: kusec_v1.SyncRun.List:input_type -> kusec_v1.SyncRunListReq
	4,  // 9: kusec_v1.SyncRun.Get:input_type -> kusec_v1.SyncRunGetReq
	3,  // 10: kusec_v1.SyncRun.List:output_type -> kusec_v1.SyncRunListRep
	1,  // 11: kusec_v1.SyncRun.Get:output_type -> kusec_v1.SyncRunMain
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_kusec_v1_syncrun_proto_init() }
func file_kusec_v1_syncrun_proto_init() {
	if File_kusec_v1_syncrun_proto != nil {
		return
	}
	file_kusec_v1_common_proto_init()
	file_kusec_v1_syncrun_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_syncrun_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_syncrun_proto_rawDesc), len(file_kusec_v1_syncrun_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_syncrun_proto_goTypes,
		DependencyIndexes: file_kusec_v1_syncrun_proto_depIdxs,
		MessageInfos:      file_kusec_v1_syncrun_proto_msgTypes,
	}.Build()
	File_kusec_v1_syncrun_proto = out.File
	file_kusec_v1_syncrun_proto_goTypes = nil
	file_kusec_v1_syncrun_proto_depIdxs = nil
}
