// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: kusec_v1/syncrun.proto

package kusec_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncRun_List_FullMethodName = "/kusec_v1.SyncRun/List"
	SyncRun_Get_FullMethodName  = "/kusec_v1.SyncRun/Get"
)

// SyncRunClient is the client API for SyncRun service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Журнал запусков синхронизации kusec → Kubernetes. Только чтение: запись
// создаётся при старте sync и финализируется в конце; чистка — фоновым
// ретеншном. Значения ключей в журнале отсутствуют — только имена
// изменившихся ключей и HMAC-отпечатки содержимого.
type SyncRunClient interface {
	List(ctx context.Context, in *SyncRunListReq, opts ...grpc.CallOption) (*SyncRunListRep, error)
	// Запуск вместе с затронутыми k8s-объектами.
	Get(ctx context.Context, in *SyncRunGetReq, opts ...grpc.CallOption) (*SyncRunMain, error)
}

type syncRunClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncRunClient(cc grpc.ClientConnInterface) SyncRunClient {
	return &syncRunClient{cc}
}

func (c *syncRunClient) List(ctx context.Context, in *SyncRunListReq, opts ...grpc.CallOption) (*SyncRunListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncRunListRep)
	err := c.cc.Invoke(ctx, SyncRun_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncRunClient) Get(ctx context.Context, in *SyncRunGetReq, opts ...grpc.CallOption) (*SyncRunMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncRunMain)
	err := c.cc.Invoke(ctx, SyncRun_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncRunServer is the server API for SyncRun service.
// All implementations must embed UnimplementedSyncRunServer
// for forward compatibility.
//
// Журнал запусков синхронизации kusec → Kubernetes. Только чтение: запись
// создаётся при старте sync и финализируется в конце; чистка — фоновым
// ретеншном. Значения ключей в журнале отсутствуют — только имена
// изменившихся ключей и HMAC-отпечатки содержимого.
type SyncRunServer interface {
	List(context.Context, *SyncRunListReq) (*SyncRunListRep, error)
	// Запуск вместе с затронутыми k8s-объектами.
	Get(context.Context, *SyncRunGetReq) (*SyncRunMain, error)
	mustEmbedUnimplementedSyncRunServer()
}

// UnimplementedSyncRunServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncRunServer struct{}

func (UnimplementedSyncRunServer) List(context.Context, *SyncRunListReq) (*SyncRunListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSyncRunServer) Get(context.Context, *SyncRunGetReq) (*SyncRunMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSyncRunServer) mustEmbedUnimplementedSyncRunServer() {}
func (UnimplementedSyncRunServer) testEmbeddedByValue()                 {}

// UnsafeSyncRunServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncRunServer will
// result in compilation errors.
type UnsafeSyncRunServer interface {
	mustEmbedUnimplementedSyncRunServer()
}

func RegisterSyncRunServer(s grpc.ServiceRegistrar, srv SyncRunServer) {
	// If the following call pancis, it indicates UnimplementedSyncRunServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncRun_ServiceDesc, srv)
}

func _SyncRun_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRunListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncRunServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncRun_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncRunServer).List(ctx, req.(*SyncRunListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncRun_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRunGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncRunServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncRun_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncRunServer).Get(ctx, req.(*SyncRunGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncRun_ServiceDesc is the grpc.ServiceDesc for SyncRun service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncRun_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kusec_v1.SyncRun",
	HandlerType: (*SyncRunServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SyncRun_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SyncRun_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kusec_v1/syncrun.proto",
}
