// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/transfer.proto

package kusec_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferTreeRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*TransferTreeAppSt   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTreeRep) Reset() {
	*x = TransferTreeRep{}
	mi := &file_kusec_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTreeRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTreeRep) ProtoMessage() {}

func (x *TransferTreeRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTreeRep.ProtoReflect.Descriptor instead.
func (*TransferTreeRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferTreeRep) GetApps() []*TransferTreeAppSt {
	if x != nil {
		return x.Apps
	}
	return nil
}

type TransferTreeAppSt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                  `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SlugName      string                  `protobuf:"bytes,4,opt,name=slug_name,json=slugName,proto3" json:"slug_name,omitempty"`
	Description   string                  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                    `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Secrets       []*TransferTreeSecretSt `protobuf:"bytes,8,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTreeAppSt) Reset() {
	*x = TransferTreeAppSt{}
	mi := &file_kusec_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTreeAppSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTreeAppSt) ProtoMessage() {}

func (x *TransferTreeAppSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTreeAppSt.ProtoReflect.Descriptor instead.
func (*TransferTreeAppSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferTreeAppSt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferTreeAppSt) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TransferTreeAppSt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransferTreeAppSt) GetSlugName() string {
	if x != nil {
		return x.SlugName
	}
	return ""
}

func (x *TransferTreeAppSt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransferTreeAppSt) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TransferTreeAppSt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TransferTreeAppSt) GetSecrets() []*TransferTreeSecretSt {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type TransferTreeSecretSt struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SlugName    string                 `protobuf:"bytes,2,opt,name=slug_name,json=slugName,proto3" json:"slug_name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active      bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Items       []*TransferTreeItemSt  `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	// Тип k8s-секрета (пусто = Opaque).
	KubeType      string `protobuf:"bytes,7,opt,name=kube_type,json=kubeType,proto3" json:"kube_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTreeSecretSt) Reset() {
	*x = TransferTreeSecretSt{}
	mi := &file_kusec_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTreeSecretSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTreeSecretSt) ProtoMessage() {}

func (x *TransferTreeSecretSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTreeSecretSt.ProtoReflect.Descriptor instead.
func (*TransferTreeSecretSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *TransferTreeSecretSt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferTreeSecretSt) GetSlugName() string {
	if x != nil {
		return x.SlugName
	}
	return ""
}

func (x *TransferTreeSecretSt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransferTreeSecretSt) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TransferTreeSecretSt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TransferTreeSecretSt) GetItems() []*TransferTreeItemSt {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TransferTreeSecretSt) GetKubeType() string {
	if x != nil {
		return x.KubeType
	}
	return ""
}

type TransferTreeItemSt struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key         string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ValueFormat string                 `protobuf:"bytes,3,opt,name=value_format,json=valueFormat,proto3" json:"value_format,omitempty"`
	Encoding    string                 `protobuf:"bytes,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	FileName    string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Description string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Active      bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Размер хранимого значения в байтах; само значение не отдаётся.
	ValueSize     int64 `protobuf:"varint,10,opt,name=value_size,json=valueSize,proto3" json:"value_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTreeItemSt) Reset() {
	*x = TransferTreeItemSt{}
	mi := &file_kusec_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTreeItemSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTreeItemSt) ProtoMessage() {}

func (x *TransferTreeItemSt) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTreeItemSt.ProtoReflect.Descriptor instead.
func (*TransferTreeItemSt) Descriptor() ([]byte, []int) {
	return file_kusec_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *TransferTreeItemSt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferTreeItemSt) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TransferTreeItemSt) GetValueFormat() string {
	if x != nil {
		return x.ValueFormat
	}
	return ""
}

func (x *TransferTreeItemSt) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *TransferTreeItemSt) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TransferTreeItemSt) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TransferTreeItemSt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransferTreeItemSt) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TransferTreeItemSt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TransferTreeItemSt) GetValueSize() int64 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

var File_kusec_v1_transfer_proto protoreflect.FileDescriptor

const file_kusec_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x17kusec_v1/transfer.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x0fTransferTreeRep\x12/\n" +
	"\x04apps\x18\x01 \x03(\v2\x1b.kusec_v1.TransferTreeAppStR\x04apps\"\xa1\x02\n" +
	"\x11TransferTreeAppSt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tslug_name\x18\x04 \x01(\tR\bslugName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\asecrets\x18\b \x03(\v2\x1e.kusec_v1.TransferTreeSecretStR\asecrets\"\x89\x02\n" +
	"\x14TransferTreeSecretSt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tslug_name\x18\x02 \x01(\tR\bslugName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\x05items\x18\x06 \x03(\v2\x1c.kusec_v1.TransferTreeItemStR\x05items\x12\x1b\n" +
	"\tkube_type\x18\a \x01(\tR\bkubeType\"\xc9\x02\n" +
	"\x12TransferTreeItemSt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12!\n" +
	"\fvalue_format\x18\x03 \x01(\tR\vvalueFormat\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\tR\bencoding\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"value_size\x18\n" +
	" \x01(\x03R\tvalueSize2]\n" +
	"\bTransfer\x12Q\n" +
	"\x04Tree\x12\x16.google.protobuf.Empty\x1a\x19.kusec_v1.TransferTreeRep\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/transfer/treeB\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_transfer_proto_rawDescOnce sync.Once
	file_kusec_v1_transfer_proto_rawDescData []byte
)

func file_kusec_v1_transfer_proto_rawDescGZIP() []byte {
	file_kusec_v1_transfer_proto_rawDescOnce.Do(func() {
		file_kusec_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_transfer_proto_rawDesc), len(file_kusec_v1_transfer_proto_rawDesc)))
	})
	return file_kusec_v1_transfer_proto_rawDescData
}

var file_kusec_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kusec_v1_transfer_proto_goTypes = []any{
	(*TransferTreeRep)(nil),       // 0: kusec_v1.TransferTreeRep
	(*TransferTreeAppSt)(nil),     // 1: kusec_v1.TransferTreeAppSt
	(*TransferTreeSecretSt)(nil),  // 2: kusec_v1.TransferTreeSecretSt
	(*TransferTreeItemSt)(nil),    // 3: kusec_v1.TransferTreeItemSt
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_kusec_v1_transfer_proto_depIdxs = []int32{
	1, // 0: kusec_v1.TransferTreeRep.apps:type_name -> kusec_v1.TransferTreeAppSt
	4, // 1: kusec_v1.TransferTreeAppSt.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: kusec_v1.TransferTreeAppSt.secrets:type_name -> kusec_v1.TransferTreeSecretSt
	4, // 3: kusec_v1.TransferTreeSecretSt.updated_at:type_name -> google.protobuf.Timestamp
	3, // 4: kusec_v1.TransferTreeSecretSt.items:type_name -> kusec_v1.TransferTreeItemSt
	4, // 5: kusec_v1.TransferTreeItemSt.updated_at:type_name -> google.protobuf.Timestamp
	5, // 6: kusec_v1.Transfer.Tree:input_type -> google.protobuf.Empty
	0, // 7: kusec_v1.Transfer.Tree:output_type -> kusec_v1.TransferTreeRep
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kusec_v1_transfer_proto_init() }
func file_kusec_v1_transfer_proto_init() {
	if File_kusec_v1_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_transfer_proto_rawDesc), len(file_kusec_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_transfer_proto_goTypes,
		DependencyIndexes: file_kusec_v1_transfer_proto_depIdxs,
		MessageInfos:      file_kusec_v1_transfer_proto_msgTypes,
	}.Build()
	File_kusec_v1_transfer_proto = out.File
	file_kusec_v1_transfer_proto_goTypes = nil
	file_kusec_v1_transfer_proto_depIdxs = nil
}
