// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: kusec_v1/usr.proto

package kusec_v1

import (
	common "github.com/mechta-market/kusec/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsrMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	AppIds        []string               `protobuf:"bytes,6,rep,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrMain) Reset() {
	*x = UsrMain{}
	mi := &file_kusec_v1_usr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrMain) ProtoMessage() {}

func (x *UsrMain) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrMain.ProtoReflect.Descriptor instead.
func (*UsrMain) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{0}
}

func (x *UsrMain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsrMain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UsrMain) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UsrMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UsrMain) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsrMain) GetAppIds() []string {
	if x != nil {
		return x.AppIds
	}
	return nil
}

type UsrListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	IsAdmin       *bool                  `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3,oneof" json:"is_admin,omitempty"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrListReq) Reset() {
	*x = UsrListReq{}
	mi := &file_kusec_v1_usr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrListReq) ProtoMessage() {}

func (x *UsrListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrListReq.ProtoReflect.Descriptor instead.
func (*UsrListReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{1}
}

func (x *UsrListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *UsrListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *UsrListReq) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

func (x *UsrListReq) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type UsrListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*UsrMain               `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsrListRep) Reset() {
	*x = UsrListRep{}
	mi := &file_kusec_v1_usr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrListRep) ProtoMessage() {}

func (x *UsrListRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrListRep.ProtoReflect.Descriptor instead.
func (*UsrListRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{2}
}

func (x *UsrListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *UsrListRep) GetResults() []*UsrMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type UsrGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrGetReq) Reset() {
	*x = UsrGetReq{}
	mi := &file_kusec_v1_usr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrGetReq) ProtoMessage() {}

func (x *UsrGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrGetReq.ProtoReflect.Descriptor instead.
func (*UsrGetReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{3}
}

func (x *UsrGetReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UsrCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        *bool                  `protobuf:"varint,1,opt,name=active,proto3,oneof" json:"active,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	AppIds        []string               `protobuf:"bytes,6,rep,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrCreateReq) Reset() {
	*x = UsrCreateReq{}
	mi := &file_kusec_v1_usr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrCreateReq) ProtoMessage() {}

func (x *UsrCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrCreateReq.ProtoReflect.Descriptor instead.
func (*UsrCreateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{4}
}

func (x *UsrCreateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *UsrCreateReq) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UsrCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UsrCreateReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsrCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UsrCreateReq) GetAppIds() []string {
	if x != nil {
		return x.AppIds
	}
	return nil
}

type UsrCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrCreateRep) Reset() {
	*x = UsrCreateRep{}
	mi := &file_kusec_v1_usr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrCreateRep) ProtoMessage() {}

func (x *UsrCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrCreateRep.ProtoReflect.Descriptor instead.
func (*UsrCreateRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{5}
}

func (x *UsrCreateRep) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UsrUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	IsAdmin       *bool                  `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3,oneof" json:"is_admin,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Username      *string                `protobuf:"bytes,5,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,6,opt,name=password,proto3,oneof" json:"password,omitempty"`
	AppIds        []string               `protobuf:"bytes,7,rep,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrUpdateReq) Reset() {
	*x = UsrUpdateReq{}
	mi := &file_kusec_v1_usr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrUpdateReq) ProtoMessage() {}

func (x *UsrUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrUpdateReq.ProtoReflect.Descriptor instead.
func (*UsrUpdateReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{6}
}

func (x *UsrUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsrUpdateReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *UsrUpdateReq) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

func (x *UsrUpdateReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UsrUpdateReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UsrUpdateReq) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UsrUpdateReq) GetAppIds() []string {
	if x != nil {
		return x.AppIds
	}
	return nil
}

type UsrLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrLoginReq) Reset() {
	*x = UsrLoginReq{}
	mi := &file_kusec_v1_usr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrLoginReq) ProtoMessage() {}

func (x *UsrLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrLoginReq.ProtoReflect.Descriptor instead.
func (*UsrLoginReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{7}
}

func (x *UsrLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsrLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UsrLoginRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrLoginRep) Reset() {
	*x = UsrLoginRep{}
	mi := &file_kusec_v1_usr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrLoginRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrLoginRep) ProtoMessage() {}

func (x *UsrLoginRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrLoginRep.ProtoReflect.Descriptor instead.
func (*UsrLoginRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{8}
}

func (x *UsrLoginRep) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *UsrLoginRep) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UsrRefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrRefreshTokenReq) Reset() {
	*x = UsrRefreshTokenReq{}
	mi := &file_kusec_v1_usr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrRefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrRefreshTokenReq) ProtoMessage() {}

func (x *UsrRefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrRefreshTokenReq.ProtoReflect.Descriptor instead.
func (*UsrRefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{9}
}

func (x *UsrRefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UsrBootstrapStatusRep struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CanCreateFirstAdmin bool                   `protobuf:"varint,1,opt,name=can_create_first_admin,json=canCreateFirstAdmin,proto3" json:"can_create_first_admin,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UsrBootstrapStatusRep) Reset() {
	*x = UsrBootstrapStatusRep{}
	mi := &file_kusec_v1_usr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrBootstrapStatusRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrBootstrapStatusRep) ProtoMessage() {}

func (x *UsrBootstrapStatusRep) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrBootstrapStatusRep.ProtoReflect.Descriptor instead.
func (*UsrBootstrapStatusRep) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{10}
}

func (x *UsrBootstrapStatusRep) GetCanCreateFirstAdmin() bool {
	if x != nil {
		return x.CanCreateFirstAdmin
	}
	return false
}

type UsrUpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrUpdateProfileReq) Reset() {
	*x = UsrUpdateProfileReq{}
	mi := &file_kusec_v1_usr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrUpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrUpdateProfileReq) ProtoMessage() {}

func (x *UsrUpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_kusec_v1_usr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrUpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UsrUpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_kusec_v1_usr_proto_rawDescGZIP(), []int{11}
}

func (x *UsrUpdateProfileReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UsrUpdateProfileReq) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UsrUpdateProfileReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

var File_kusec_v1_usr_proto protoreflect.FileDescriptor

const file_kusec_v1_usr_proto_rawDesc = "" +
	"\n" +
	"\x12kusec_v1/usr.proto\x12\bkusec_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\"\x95\x01\n" +
	"\aUsrMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x17\n" +
	"\aapp_ids\x18\x06 \x03(\tR\x06appIds\"\xc0\x01\n" +
	"\n" +
	"UsrListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x1e\n" +
	"\bis_admin\x18\x03 \x01(\bH\x01R\aisAdmin\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x02R\x06search\x88\x01\x01B\t\n" +
	"\a_activeB\v\n" +
	"\t_is_adminB\t\n" +
	"\a_search\"|\n" +
	"\n" +
	"UsrListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x12+\n" +
	"\aresults\x18\x02 \x03(\v2\x11.kusec_v1.UsrMainR\aresults\"\x1b\n" +
	"\tUsrGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb6\x01\n" +
	"\fUsrCreateReq\x12\x1b\n" +
	"\x06active\x18\x01 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x17\n" +
	"\aapp_ids\x18\x06 \x03(\tR\x06appIdsB\t\n" +
	"\a_active\"\x1e\n" +
	"\fUsrCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8a\x02\n" +
	"\fUsrUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x1e\n" +
	"\bis_admin\x18\x03 \x01(\bH\x01R\aisAdmin\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x02R\x04name\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x05 \x01(\tH\x03R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x06 \x01(\tH\x04R\bpassword\x88\x01\x01\x12\x17\n" +
	"\aapp_ids\x18\a \x03(\tR\x06appIdsB\t\n" +
	"\a_activeB\v\n" +
	"\t_is_adminB\a\n" +
	"\x05_nameB\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"E\n" +
	"\vUsrLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"D\n" +
	"\vUsrLoginRep\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"9\n" +
	"\x12UsrRefreshTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"L\n" +
	"\x15UsrBootstrapStatusRep\x123\n" +
	"\x16can_create_first_admin\x18\x01 \x01(\bR\x13canCreateFirstAdmin\"\x93\x01\n" +
	"\x13UsrUpdateProfileReq\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x01R\bpassword\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x02R\busername\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_passwordB\v\n" +
	"\t_username2\xbb\x06\n" +
	"\x03Usr\x12@\n" +
	"\x04List\x12\x14.kusec_v1.UsrListReq\x1a\x14.kusec_v1.UsrListRep\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/usr\x12@\n" +
	"\x03Get\x12\x13.kusec_v1.UsrGetReq\x1a\x11.kusec_v1.UsrMain\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/usr/{id}\x12I\n" +
	"\x06Create\x12\x16.kusec_v1.UsrCreateReq\x1a\x16.kusec_v1.UsrCreateRep\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/usr\x12N\n" +
	"\x06Update\x12\x16.kusec_v1.UsrUpdateReq\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/usr/{id}\x12H\n" +
	"\x06Delete\x12\x13.kusec_v1.UsrGetReq\x1a\x16.google.protobuf.Empty\"\x11\x82\xd3\xe4\x93\x02\v*\t/usr/{id}\x12L\n" +
	"\x05Login\x12\x15.kusec_v1.UsrLoginReq\x1a\x15.kusec_v1.UsrLoginRep\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/usr/login\x12b\n" +
	"\fRefreshToken\x12\x1c.kusec_v1.UsrRefreshTokenReq\x1a\x15.kusec_v1.UsrLoginRep\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/usr/token/refresh\x12i\n" +
	"\x0fBootstrapStatus\x12\x16.google.protobuf.Empty\x1a\x1f.kusec_v1.UsrBootstrapStatusRep\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/usr/bootstrap/status\x12M\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x11.kusec_v1.UsrMain\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/usr/profile\x12_\n" +
	"\rUpdateProfile\x12\x1d.kusec_v1.UsrUpdateProfileReq\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/usr/profileB\vZ\t/kusec_v1b\x06proto3"

var (
	file_kusec_v1_usr_proto_rawDescOnce sync.Once
	file_kusec_v1_usr_proto_rawDescData []byte
)

func file_kusec_v1_usr_proto_rawDescGZIP() []byte {
	file_kusec_v1_usr_proto_rawDescOnce.Do(func() {
		file_kusec_v1_usr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kusec_v1_usr_proto_rawDesc), len(file_kusec_v1_usr_proto_rawDesc)))
	})
	return file_kusec_v1_usr_proto_rawDescData
}

var file_kusec_v1_usr_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kusec_v1_usr_proto_goTypes = []any{
	(*UsrMain)(nil),                 // 0: kusec_v1.UsrMain
	(*UsrListReq)(nil),              // 1: kusec_v1.UsrListReq
	(*UsrListRep)(nil),              // 2: kusec_v1.UsrListRep
	(*UsrGetReq)(nil),               // 3: kusec_v1.UsrGetReq
	(*UsrCreateReq)(nil),            // 4: kusec_v1.UsrCreateReq
	(*UsrCreateRep)(nil),            // 5: kusec_v1.UsrCreateRep
	(*UsrUpdateReq)(nil),            // 6: kusec_v1.UsrUpdateReq
	(*UsrLoginReq)(nil),             // 7: kusec_v1.UsrLoginReq
	(*UsrLoginRep)(nil),             // 8: kusec_v1.UsrLoginRep
	(*UsrRefreshTokenReq)(nil),      // 9: kusec_v1.UsrRefreshTokenReq
	(*UsrBootstrapStatusRep)(nil),   // 10: kusec_v1.UsrBootstrapStatusRep
	(*UsrUpdateProfileReq)(nil),     // 11: kusec_v1.UsrUpdateProfileReq
	(*common.ListParamsSt)(nil),     // 12: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 13: common.PaginationInfoSt
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_kusec_v1_usr_proto_depIdxs = []int32{
	12, // 0: kusec_v1.UsrListReq.list_params:type_name -> common.ListParamsSt
	13, // 1: kusec_v1.UsrListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 2: kusec_v1.UsrListRep.results:type_name -> kusec_v1.UsrMain
	1,  // 3: kusec_v1.Usr.List:input_type -> kusec_v1.UsrListReq
	3,  // 4: kusec_v1.Usr.Get:input_type -> kusec_v1.UsrGetReq
	4,  // 5: kusec_v1.Usr.Create:input_type -> kusec_v1.UsrCreateReq
	6,  // 6: kusec_v1.Usr.Update:input_type -> kusec_v1.UsrUpdateReq
	3,  // 7: kusec_v1.Usr.Delete:input_type -> kusec_v1.UsrGetReq
	7,  // 8: kusec_v1.Usr.Login:input_type -> kusec_v1.UsrLoginReq
	9,  // 9: kusec_v1.Usr.RefreshToken:input_type -> kusec_v1.UsrRefreshTokenReq
	14, // 10: kusec_v1.Usr.BootstrapStatus:input_type -> google.protobuf.Empty
	14, // 11: kusec_v1.Usr.GetProfile:input_type -> google.protobuf.Empty
	11, // 12: kusec_v1.Usr.UpdateProfile:input_type -> kusec_v1.UsrUpdateProfileReq
	2,  // 13: kusec_v1.Usr.List:output_type -> kusec_v1.UsrListRep
	0,  // 14: kusec_v1.Usr.Get:output_type -> kusec_v1.UsrMain
	5,  // 15: kusec_v1.Usr.Create:output_type -> kusec_v1.UsrCreateRep
	14, // 16: kusec_v1.Usr.Update:output_type -> google.protobuf.Empty
	14, // 17: kusec_v1.Usr.Delete:output_type -> google.protobuf.Empty
	8,  // 18: kusec_v1.Usr.Login:output_type -> kusec_v1.UsrLoginRep
	8,  // 19: kusec_v1.Usr.RefreshToken:output_type -> kusec_v1.UsrLoginRep
	10, // 20: kusec_v1.Usr.BootstrapStatus:output_type -> kusec_v1.UsrBootstrapStatusRep
	0,  // 21: kusec_v1.Usr.GetProfile:output_type -> kusec_v1.UsrMain
	14, // 22: kusec_v1.Usr.UpdateProfile:output_type -> google.protobuf.Empty
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kusec_v1_usr_proto_init() }
func file_kusec_v1_usr_proto_init() {
	if File_kusec_v1_usr_proto != nil {
		return
	}
	file_kusec_v1_usr_proto_msgTypes[1].OneofWrappers = []any{}
	file_kusec_v1_usr_proto_msgTypes[4].OneofWrappers = []any{}
	file_kusec_v1_usr_proto_msgTypes[6].OneofWrappers = []any{}
	file_kusec_v1_usr_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kusec_v1_usr_proto_rawDesc), len(file_kusec_v1_usr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kusec_v1_usr_proto_goTypes,
		DependencyIndexes: file_kusec_v1_usr_proto_depIdxs,
		MessageInfos:      file_kusec_v1_usr_proto_msgTypes,
	}.Build()
	File_kusec_v1_usr_proto = out.File
	file_kusec_v1_usr_proto_goTypes = nil
	file_kusec_v1_usr_proto_depIdxs = nil
}
