name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: yc-arc
    env:
      OWNER: mechta-market
      IMAGE: kusec:latest
    steps:
      - uses: actions/checkout@v6

      - run: go mod download

      # - run: go test -v ./...

      - run: make

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - run: docker build -f deploy/docker/Dockerfile -t ghcr.io/$OWNER/$IMAGE .

      - run: docker push ghcr.io/$OWNER/$IMAGE
